tools/buildmgr/cbuild/include/Cbuild.h, tools/buildmgr/cbuild/include/CbuildLayer.h, tools/buildmgr/cbuild/src/Cbuild.cpp, tools/buildmgr/cbuild/src/CbuildLayer.cpp, tools/buildmgr/cbuild/src/CbuildMsgs.cpp, tools/buildmgr/cbuildgen/src/Console.cpp, tools/buildmgr/docs/doxygen/Build/src/CmdLineBuild.txt, tools/buildmgr/test/integrationtests/src/CBuildGenTestFixture.cpp, tools/buildmgr/test/testinput/Examples/Layers/Layers_Compose/Project_Ref/Blinky_Device.c, tools/buildmgr/test/testinput/Examples/Layers/Layers_Compose/Project_Ref/Simulation.cprj, tools/buildmgr/test/testinput/Examples/Layers/Layers_Extract/Layer_Ref/application/Blinky.c, tools/buildmgr/test/testinput/Examples/Layers/Layers_Extract/Layer_Ref/application/application.clayer, tools/buildmgr/test/testinput/Examples/Layers/Layers_Extract/Layer_Ref/device/device.clayer
Add layer compose options for setting project name and description
Set info name field in extracted layer
Update tests and documentation
=> buildmgr: Add layer compose options

tools/buildmgr/cbuild/src/CbuildModel.cpp
Bugfix: layer extraction misses files in generated (GPDSC) bundles
=> [buildmgr] Associate files from GPDSC bundled components to layers

tools/packgen/include/PackGen.h, tools/packgen/schema/manifest.schema.json, tools/packgen/src/PackGen.cpp, tools/packgen/test/data/TestProject/TestVendor.TestPack.pdsc, tools/packgen/test/data/TestProject/manifest.yml, tools/packgen/test/data/TestProject/out-of-root/TestVendor.TestPackOutOfRoot.pdsc, tools/packgen/test/data/TestProject/out-of-root/manifest.yml, tools/packgen/test/src/PackGenUnitTests.cpp
Update yaml schema.
Extend test cases.
=> [packgen] Add 'repository' field and extend 'releases' attributes.

tools/buildmgr/cbuildgen/config/AC5.5.6.7.cmake, tools/buildmgr/cbuildgen/config/GCC.10.2.1.cmake, tools/buildmgr/cbuildgen/config/setup, tools/buildmgr/cbuildgen/installer/create_installer.sh, tools/buildmgr/docs/doxygen/Build/Build.dxy, tools/buildmgr/docs/doxygen/Build/src/CmdLineBuild.txt, tools/buildmgr/docs/doxygen/Build/src/General.txt
- Update version/date in toolchain config files
- Remove version from internal script
- Update documentation
=> [buildmgr] Add release notes (#77)

.github/doxygen.json, .github/linkchecker.json, .github/workflows/buildmgr.yml, scripts/check_links.sh
- Add problem-matcher for doxygen warnings.
- Add LinkChecker to verify hyperlinks.
=> GitHub: Enable checks for buildmgr documentation.

libs/rtemodel/src/RteDevice.cpp, libs/rtemodel/test/src/RteModelTest.cpp, test/packs/ARM/RteTest_DFP/0.1.1/ARM.RteTest_DFP.pdsc
=> Device summary string: use IsWriteAccess() and IsReadAccess() for RAM and ROM count (#104)

tools/packchk/src/CheckFiles.cpp, tools/packchk/test/unittests/CMakeLists.txt, tools/packchk/test/unittests/src/TestCheckFiles.cpp, tools/packchk/test/unittests/src/TestPackOptions.cpp, tools/packchk/test/unittests/src/TestValidateSyntax.cpp
* fixed IsDirectory() test for category "include"
* added regression test case 
Fixes isse #111
Co-authored-by: Jonatan Antoni <jonatan.antoni@arm.com>
=> packchk: wrong ERROR M339

tools/projmgr/docs/Manual/Overview.md
Added more information for "Access Sequences" and for CMSIS-Zone Integration (resource, requirements).
=>  Update Access Sequences and for CMSIS-Zone Integration

CMakeLists.txt, external/json.patch, libs/ymlschemachecker/src/SchemaErrorHandler.cpp, libs/ymlschemachecker/src/SchemaErrorHandler.h, libs/ymlschemachecker/src/SchemaValidator.cpp, libs/ymlschemachecker/test/src/SchemaChkTests.cpp
* [ymlschemachecker] Uniform error output
* fixed review comments
* Catch exception with line and col info
* Cleaned error msg
=> [ymlschemachecker] Uniform error output (#116)

test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, tools/buildmgr/cbuild/src/CbuildProject.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestProject/test.cproject_board_multi_variant.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
[buildmgr] Fix warning message when selecting device variant automatically
=> [projmgr] Add device variants check when resolving selected device, add test case

libs/rtefsutils/include/RteFsUtils.h, libs/rtefsutils/src/RteFsUtils.cpp, libs/rtemodel/include/RteCallback.h, libs/rtemodel/include/RteProject.h, libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/test/src/RteModelTest.cpp, libs/rteutils/include/RteUtils.h, libs/rteutils/src/RteUtils.cpp, libs/rteutils/test/src/RteUtilsTest.cpp, test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, test/projects/RteTestM3/CONFIG_FOLDER/Device/RteTest_ARMCM3/.ARMCM3_ac6.sct@1.0.0, test/projects/RteTestM3/CONFIG_FOLDER/Device/RteTest_ARMCM3/.startup_ARMCM3.c@2.0.3, test/projects/RteTestM3/CONFIG_FOLDER/Device/RteTest_ARMCM3/.system_ARMCM3.c@1.0.1, tools/projmgr/test/data/TestLayers/ref/testlayers.Debug/RTE/Device/RteTest_ARMCM0/.ARMCM0_ac6.sct@1.0.0, tools/projmgr/test/data/TestLayers/ref/testlayers.Debug/RTE/Device/RteTest_ARMCM0/.startup_ARMCM0.c@2.0.3, tools/projmgr/test/data/TestLayers/ref/testlayers.Debug/RTE/Device/RteTest_ARMCM0/.system_ARMCM0.c@1.0.0, tools/projmgr/test/data/TestLayers/ref/testlayers.Release/RTE/Device/RteTest_ARMCM0/.ARMCM0_ac6.sct@1.0.0, tools/projmgr/test/data/TestLayers/ref/testlayers.Release/RTE/Device/RteTest_ARMCM0/.startup_ARMCM0.c@2.0.3, tools/projmgr/test/data/TestLayers/ref/testlayers.Release/RTE/Device/RteTest_ARMCM0/.system_ARMCM0.c@1.0.0, tools/projmgr/test/data/TestLayers/ref/testlayers.Release/RTE/RteTest/.ComponentLevelConfig_0.h@0.0.1, tools/projmgr/test/data/TestLayers/ref/testlayers.Release/RTE/RteTest/MyDir/.RelativeComponentLevelConfig_0.h@0.0.1, tools/projmgr/test/data/TestSolution/TestProject2/test2.Debug+CM3.cprj, tools/projmgr/test/data/TestSolution/TestProject2/test2.Debug+CM3_pname.cprj
* RteModel: handling config file versions
* RteModel: handling config file versions
Bugfixes and tests
* RteModel: handling config file versions
Review actions
* Update ProjMgrUnitTests test cases
* RteModel: handling config file versions
Updated tests and Test files
=> Config files plm (#140)

tools/projmgr/schemas/clayer.schema.json, tools/projmgr/schemas/cproject.schema.json, tools/projmgr/schemas/csolution.schema.json
Proposal in sync. #83 
Such will preserve current OpenCMSIS proposal and is allowing integrator to promote its own schema on top of.
=> [projmgr] Open door to vendor specific data addon

tools/buildmgr/cbuildgen/config/IAR.8.50.6.cmake, tools/buildmgr/cbuildgen/installer/install.sh
=> support IAR C/C++ Compiler V8.50.6.265/W32 for ARM (#115)

.github/workflows/buildmgr.yml
The release step missed to stage the latest link.
=> Fix workflow publishing buildmgr documentation.

libs/rtemodel/src/CprjFile.cpp, libs/rtemodel/src/RteBoard.cpp
* fix finding board for cprj target
* Update libs/rtemodel/src/CprjFile.cpp
* Update libs/rtemodel/src/RteBoard.cpp
=> fix finding board for cprj target (#162)

libs/crossplatform/include/CrossPlatformUtils.h, libs/crossplatform/src/CrossPlatformUtils.cpp, libs/crossplatform/src/Darwin/Utils.cpp, libs/crossplatform/src/Darwin/constants.h, libs/crossplatform/src/Emscripten/constants.h, libs/crossplatform/src/Linux/Utils.cpp, libs/crossplatform/src/Linux/constants.h, libs/crossplatform/src/Windows/Utils.cpp, libs/crossplatform/src/Windows/constants.h, libs/crossplatform/test/src/UnitTests.cpp, libs/rtemodel/CMakeLists.txt, libs/rtemodel/src/RteItem.cpp
* CrossPlatform: registry operation and host type
* Update libs/crossplatform/test/src/UnitTests.cpp
* Update libs/crossplatform/src/Windows/Utils.cpp
* Update libs/crossplatform/include/CrossPlatformUtils.h
* Update libs/crossplatform/src/Windows/Utils.cpp
* CrossPlatform: registry operation and host type
Review corrections
* CrossPlatform: registry operation and host type
Review corrections
=> CrossPlatform: registry operation and host type (#168)

test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc, test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.sh, tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Add execute Generator test for Linux
* Add execute Generator test for Linux
set +x for the script.sh
=> Add execute Generator test for Linux (#173)

tools/buildmgr/cbuildgen/scripts/cbuild.sh, tools/buildmgr/docs/cbuild.md, tools/buildmgr/docs/doxygen/Build/src/CmdLineBuild.txt
* [buildmgr] Update help menu
* Address review comment
Co-authored-by: Sourabh Mehta <73165318+soumeh01@users.noreply.github.com>
Co-authored-by: Sourabh Mehta <73165318+soumeh01@users.noreply.github.com>
=> [buildmgr] Update help menu (#174)

tools/buildmgr/cbuildgen/config/CPRJ.xsd
Initial CPRJ schema extensions draft for https://github.com/Open-CMSIS-Pack/devtools/issues/179
=> Proposal: CPRJ schema extensions

libs/crossplatform/src/Windows/Utils.cpp, libs/crossplatform/test/src/UnitTests.cpp, libs/rtemodel/include/RteGenerator.h, libs/rtemodel/src/RteGenerator.cpp, test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestGenerator/test-gpdsc_with_key.cproject.yml, tools/projmgr/test/data/TestGenerator/test-gpdsc_with_key.csolution.yml, tools/projmgr/test/data/TestSolution/pack_contexts.cproject.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Generator: support for "key" attribute
* Update libs/rtemodel/src/RteGenerator.cpp
* Generator: support for "key" attribute : test fix
=> Generator: support for "key" attribute (#176)

libs/rteutils/src/DeviceVendor.cpp, libs/rteutils/test/src/RteUtilsTest.cpp
old name OOSemiconductor:141 is also added
=> added device vendor onsemi:141 (#203)

libs/rtemodel/src/RteBoard.cpp
=> Debug probe from board description: respect empty Pname attribute (#214)

tools/projmgr/schemas/common.schema.json
* [projmgr] Update board and device schema requirements
* Address review comments
=> [projmgr] Update board and device schema requirements (#216)

libs/rtefsutils/include/RteFsUtils.h, libs/rtefsutils/src/RteFsUtils.cpp, libs/rtefsutils/test/src/RteFsUtilsTest.cpp, libs/rtemodel/src/RteKernel.cpp, libs/rtemodel/test/src/RteModelTest.cpp, tools/buildmgr/cbuild/src/CbuildProject.cpp
Fixes issue https://github.com/Open-CMSIS-Pack/devtools/issues/299
=> [rtefsutils, rtemodel, cbuild] Fix local file URLs handling (#221)

tools/buildmgr/cbuildgen/config/IAR.8.50.6.cmake
fix #219 
Here is a a working patch on my side
@fred-r
@tarek-bochkati
=> IAR build patch

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
* [projmgr] Rework list packs
* [projmgr] Address review comments
=> [projmgr] Rework list packs (#245)

tools/projmgr/schemas/common.schema.json
Add capability to define custom output directories.
=> [csolution] [cbuild] directory tree gets difficult to use.

tools/projmgr/docs/Manual/YML-Format.md
- define:, undefine:, add-path:, del-path:  (plural optional)
- output-dirs: added
- for-compiler: added (for group, file, and setup)
- setups: added (enables compiler specific controls)
- misc: C* changed to C-CPP
- misc: compiler: changed to for-compiler: (now optional)
=> Changes to YML-Format:

tools/packchk/src/ValidateSyntax.cpp, tools/packchk/test/data/TestSON/TestVendor.TestSON.pdsc, tools/packchk/test/integtests/src/PackChkIntegTests.cpp
added:
- Device Feature "SON"
- Test against feature "SON (ok) and "SOX" (throws error)
=> PackChk (#246)

.github/workflows/packchk.yml
- Don't archive coverage as zip in zip
- Include lcov information in archive
- Add branch information to lcov
=> Update code coverage steps

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
* [projmgr] Reworked 'device not found' message
* Resolved warning by removing escape character
=> [projmgr] Reworked 'device not found' message (#278)

.github/workflows/buildmgr.yml, .github/workflows/codeql-analysis.yml, .github/workflows/packchk.yml, .github/workflows/packgen.yml, .github/workflows/projmgr.yml, .github/workflows/test_libs.yml
... when only documentation is touched
=> GitHub: Don't trigger source code checks

libs/ymlschemachecker/test/data/csettings.schema.json, libs/ymlschemachecker/test/data/sample-data/csolution.yaml, tools/buildmgr/cbuildgen/config/CPRJ.xsd, tools/projmgr/docs/Manual/Overview.md, tools/projmgr/docs/Manual/YML-Input-Format.md, tools/projmgr/docs/Template/MySolution.csolution.yml, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/test.csolution.yml, tools/projmgr/test/data/TestSolution/test.csolution_filtered_pack_selection.yml, tools/projmgr/test/data/TestSolution/test.csolution_invalid_pack.yml, tools/projmgr/test/data/TestSolution/test.csolution_list_board_package.yml, tools/projmgr/test/data/TestSolution/test.csolution_local_pack_file_not_found.yml, tools/projmgr/test/data/TestSolution/test.csolution_local_pack_path.yml, tools/projmgr/test/data/TestSolution/test.csolution_local_pack_path_not_found.yml, tools/projmgr/test/data/TestSolution/test.csolution_missing_project.yml, tools/projmgr/test/data/TestSolution/test.csolution_no_buildtypes.yml, tools/projmgr/test/data/TestSolution/test.csolution_no_device_name.yml, tools/projmgr/test/data/TestSolution/test.csolution_no_packs.yml, tools/projmgr/test/data/TestSolution/test.csolution_pack_selection.yml, tools/projmgr/test/data/TestSolution/test.csolution_pname.yml
Signed-off-by: Tarek BOCHKATI [tarek.bouchkati@st.com](mailto:tarek.bouchkati@st.com)
=> [projmgr,buildmgr] make optimize and warnings types more generic

tools/projmgr/include/ProjMgrGenerator.h, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/test/data/TestSolution/ref/test.target_options+CM0.cprj, tools/projmgr/test/data/TestSolution/test.target_options.cproject.yml, tools/projmgr/test/data/TestSolution/test.target_options.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
=> [projmgr] ProjMgrGenerator: add GenerateCprjOptions

libs/rtemodel/include/RteItem.h, libs/rtemodel/src/RteItem.cpp, libs/rtemodel/test/src/RteModelTest.cpp, tools/buildmgr/cbuild/include/CbuildModel.h, tools/buildmgr/cbuild/src/CbuildModel.cpp, tools/buildmgr/cbuildgen/include/BuildSystemGenerator.h, tools/buildmgr/cbuildgen/src/BuildSystemGenerator.cpp, tools/buildmgr/cbuildgen/src/CMakeListsGenerator.cpp, tools/buildmgr/test/integrationtests/src/CBuildGenTests.cpp, tools/buildmgr/test/testinput/Examples/GCC/TranslationControl/Project3/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/GCC/TranslationControl/Project3/File.c, tools/buildmgr/test/testinput/Examples/GCC/TranslationControl/Project3/File2.cpp, tools/buildmgr/test/testinput/Examples/GCC/TranslationControl/Project3/Project.cprj, tools/buildmgr/test/unittests/src/CbuildModelTests.cpp
=> [buildmgr] support target TranslateCtrls options

tools/projmgr/docs/Manual/Generator (Proposal).md, tools/projmgr/docs/Manual/YML-CBuild-Format.md
CBuild-Format: `csolution:` node added, `projects:` -> `contexts:`, `selected-by:` reduced to component name only.
=> Generator: consistency of `genlayer.yml` file name

tools/projmgr/docs/Manual/YML-Input-Format.md
This update is linked to PR #478 
=> [projmgr] update optimize and warnings documentation

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/outdirs-absolute.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
[projmgr] Fix layer's compiler processing
=> [projmgr] Ensure custom dirs are relative

libs/rtemodel/src/RteProject.cpp, libs/rtemodel/test/src/RteModelTest.cpp, test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, tools/projmgr/test/data/TestSolution/ref/test2.Debug+CM3.cprj, tools/projmgr/test/data/TestSolution/ref/test2.Debug+CM3_pname.cprj
* PLM of config files
discover file version from .base file
=> PLM of config files (#346)

tools/buildmgr/cbuildgen/config/AC6.6.18.0.cmake, tools/buildmgr/cbuildgen/config/CPRJ.xsd, tools/buildmgr/cbuildgen/include/BuildSystemGenerator.h, tools/buildmgr/cbuildgen/src/BuildSystemGenerator.cpp, tools/buildmgr/cbuildgen/src/CMakeListsGenerator.cpp, tools/buildmgr/test/integrationtests/src/CBuildAC6Tests.cpp, tools/buildmgr/test/integrationtests/src/CBuildGCCTests.cpp, tools/buildmgr/test/integrationtests/src/CBuildGenTests.cpp, tools/buildmgr/test/integrationtests/src/CBuildTestFixture.cpp, tools/buildmgr/test/integrationtests/src/CBuildTestFixture.h, tools/buildmgr/test/scripts/download_packs.sh, tools/buildmgr/test/testinput/Examples/AC6/BranchProtection/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/AC6/BranchProtection/Project.cprj, tools/buildmgr/test/testinput/Examples/AC6/BranchProtection/main.c, tools/buildmgr/test/testinput/Examples/AC6/Build_AC6/Simulation.fixed.cprj.ref, tools/buildmgr/test/testinput/Examples/GCC/BranchProtection/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/GCC/BranchProtection/Project.cprj, tools/buildmgr/test/testinput/Examples/GCC/BranchProtection/main.c
* [buildmgr] Add support for Branch Protection
Update CPRJ xml schema
Add target attribute DbranchProt and enumeration values DbranchProtEnum
Add AC6 options mapping
Extend test cases
* [buildmgr] Fix CheckCompileCommand
=> [buildmgr] Add support for Branch Protection (#347)

.github/workflows/buildmgr.yml, .github/workflows/codeql-analysis.yml, .github/workflows/global.yaml, .github/workflows/markdown.yml, .github/workflows/packchk.yml, .github/workflows/packgen.yml, .github/workflows/projmgr.yml, .github/workflows/svdconv.yml, .github/workflows/test_libs.yml, .github/workflows/unit_test_results.yml
* Many warnings due to deprecation of nodejs node12
* set-output changes
=> Fixing github actions warnings (#352)

tools/projmgr/docs/Manual/Overview.md, tools/projmgr/docs/Manual/YML-Input-Format.md
- Removed `device:` and `board:` definition from cproject.yml
- Added `type:` to layer, unnamed `layer:` replaces `layer-templates:`
- Added `for-board:` and `for-device:` to `layer:` node of the clayer.yml file.
- Added Proposals for `layers:`
- Reworked description of `interface:` node
=> Reworked documentation:

libs/rtemodel/include/RteDevice.h, libs/rtemodel/include/RteInstance.h, libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/CprjFile.cpp, libs/rtemodel/src/RteAttributes.cpp, libs/rtemodel/src/RteBoard.cpp, libs/rtemodel/src/RteComponent.cpp, libs/rtemodel/src/RteCprjProject.cpp, libs/rtemodel/src/RteDevice.cpp, libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/src/RteModel.cpp, libs/rtemodel/src/RtePackage.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp, libs/rteutils/src/DeviceVendor.cpp, libs/rteutils/test/src/RteUtilsTest.cpp, libs/xmltree/src/XMLTree.cpp, libs/xmltreeslim/src/XmlTreeSlimInterface.cpp
* Fix CodeQL warnings in RteModel
warning removed
3PEAK:177  vendor is added
=> Fix CodeQL warnings in RteModel

README.md
Signed-off-by: yvesll <toyears@hotmail.com>
=> [BuildMgr] Add gnu-tar and gzip requirement for apple silicon

tools/buildmgr/cbuildgen/installer/create_installer.sh, tools/buildmgr/cbuildgen/installer/install.sh
Fix issue https://github.com/Open-CMSIS-Pack/devtools/issues/547
=> [buildmgr] Allow darwin-amd64 for arm64 install while lacking native support

tools/packchk/src/ValidateSyntax.cpp
added missing features from Device and Board table:
https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd#L932
=> GitHub#469 (#362)

test/packs/ARM/RteTest_DFP/0.2.0/Layers/board1.clayer.yml, test/packs/ARM/RteTest_DFP/0.2.0/Layers/board2.clayer.yml, test/packs/ARM/RteTest_DFP/0.2.0/Layers/incompatible.clayer.yml, test/packs/ARM/RteTest_DFP/0.2.0/Layers/testvariant.clayer.yml, tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrLogger.h, tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrUtils.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrLogger.cpp, tools/projmgr/src/ProjMgrParser.cpp, tools/projmgr/src/ProjMgrUtils.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestLayers/genericlayers.cproject.yml, tools/projmgr/test/data/TestLayers/genericlayers.csolution.yml, tools/projmgr/test/data/TestLayers/ref/interfaces/interfaces.CompatibleInterfaces.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrUtilsUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Validate interfaces
Discover matching layers
Add `list layers` command
Add test cases
=> [projmgr] Add layers interfaces validation and matching (#391)

tools/svdconv/SVDConv/include/ParseOptions.h, tools/svdconv/SVDConv/include/SvdOptions.h, tools/svdconv/SVDConv/src/ParseOptions.cpp, tools/svdconv/SVDConv/src/SvdOptions.cpp, tools/svdconv/SVDGenerator/src/SfrccInterface.cpp, tools/svdconv/SVDGenerator/src/SvdGenerator.cpp, tools/svdconv/Test/data/option_n/option_n.svd, tools/svdconv/Test/integtests/src/SvdConvIntegTests.cpp, tools/svdconv/Test/integtests/src/SvdConvTestCmdLine.cpp
* Added: option "-n sfdOverwriteName"
* fixed remaining issues
=> Added: option "-n sfdOverwriteName" (#392)

test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, test/packs/ARM/RteTest_DFP/0.2.0/Layers/board3.clayer.yml, test/packs/ARM/RteTest_DFP/0.2.0/Layers/pdsc-type-mismatch.clayer.yml, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/genericlayers.cproject.yml, tools/projmgr/test/data/TestLayers/genericlayers.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
* [projmgr] Integrate layers from packs retrieval
=> [projmgr] Integrate layers from packs retrieval (#395)

tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/config.clayer.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Increase debug verbosity of connections iterations
=> [projmgr] Handle multiple common `connect` nodes

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/variables-notdefined.cproject.yml, tools/projmgr/test/data/TestLayers/variables-notdefined.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address [#643 item 5](https://github.com/Open-CMSIS-Pack/devtools/issues/643#issue-1508110517)
=> [projmgr] Decrease severity when variables for layer paths are not defined (#423)

tools/projmgr/src/ProjMgrUtils.cpp, tools/projmgr/test/src/ProjMgrUtilsUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/667
=> [projmgr] Add support for IAR linker script extension `.icf` (#427)

tools/svdconv/SVDModel/include/SvdTypes.h, tools/svdconv/SVDModel/src/SvdTypes.cpp, tools/svdconv/SVDModel/src/SvdUtils.cpp, tools/svdconv/Test/UnitTests/src/SvdUtilsTest.cpp
- Add table that converts using a loop
- Add test case
=> [svdconv] Code cleanup

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
* [projmgr] Refine valid configurations info output
=> [projmgr] Refine valid configurations info output (#446)

libs/rtemodel/src/RteFile.cpp, libs/rtemodel/test/src/RteModelTest.cpp
=> Issue #676: Custom RTE directory computation replaces whitespaces (#457)

libs/rtemodel/include/RteCondition.h, libs/rtemodel/src/RteCondition.cpp, libs/rtemodel/test/CMakeLists.txt, libs/rtemodel/test/src/RteConditionTest.cpp, libs/rtemodel/test/src/RteExampleTest.cpp, libs/rtemodel/test/src/RteModelTest.cpp, libs/rtemodel/test/src/RteModelTestConfig.cpp, libs/rtemodel/test/src/RteModelTestConfig.h
=> RteConditionExpression: evaluate to IGNORED for unknown domain (#460)

tools/svdconv/SVDGenerator/src/MemoryMap.cpp
=> CodeQL fixes (#465)

tools/packchk/src/PackChk_Msgs.cpp
Fixes Open-CMSIS-Pack/devtools#139
=> PackChk: Changed M377 from INFO to WARNING

libs/rtemodel/include/RteGenerator.h, libs/rtemodel/src/RteComponent.cpp, libs/rtemodel/src/RteGenerator.cpp, libs/rtemodel/src/RteProject.cpp, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestGenerator/RTE/_test-gpdsc.Debug_CM0/RTE_Components.h, tools/projmgr/test/data/TestGenerator/layer/test.clayer.yml, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-layer.Debug+CM0.cprj, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestGenerator/test-gpdsc-layer.cproject.yml, tools/projmgr/test/data/TestGenerator/test-gpdsc-layer.csolution.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Release+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/outputFiles.Debug+Target.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/outputFiles.Library+Target.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
* [devtools] Add `gendir` component instance attribute
=> [devtools] Add `gendir` component instance attribute (#385)

tools/packchk/src/CheckFiles.cpp
- extracted filename for the check
- now checking whole path
- added detection of SVD files from pack
- moved detection code outside "CheckFileExist()"
=> PackChk should check for spaces in the name element of the <file> tag (#469)

libs/rtemodel/include/RteFile.h, libs/rtemodel/include/RteInstance.h, libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/RteComponent.cpp, libs/rtemodel/src/RteFile.cpp, libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp, tools/buildmgr/test/unittests/src/UtilsTests.cpp, tools/projmgr/schemas/common.schema.json
* [RTE Model] Add support for new file attributes language and scope #701
includes:  [RTE Model/csolution] extend: FileCategoryType #722
=> [RTE Model] Add support for new file attributes language and scope #701 (#477)

.gitignore, .gitmodules, CMakeLists.txt, external/xerces-c.patch, libs/xmlschemachecker/CMakeLists.txt, libs/xmlschemachecker/include/XmlChecker.h, libs/xmlschemachecker/src/XmlChecker.cpp, libs/xmlschemachecker/src/XmlErrorHandler.cpp, libs/xmlschemachecker/src/XmlErrorHandler.h, libs/xmlschemachecker/src/XmlValidator.cpp, libs/xmlschemachecker/src/XmlValidator.h, libs/xmlschemachecker/test/CMakeLists.txt, libs/xmlschemachecker/test/data/invalid.pdsc, libs/xmlschemachecker/test/data/valid.pdsc, libs/xmlschemachecker/test/src/XmlValidatorTest.cpp, tools/packchk/CMakeLists.txt, tools/packchk/README.md, tools/packchk/include/CreateModel.h, tools/packchk/include/PackOptions.h, tools/packchk/include/ParseOptions.h, tools/packchk/src/CreateModel.cpp, tools/packchk/src/PackChk.cpp, tools/packchk/src/PackChk_Msgs.cpp, tools/packchk/src/PackOptions.cpp, tools/packchk/src/ParseOptions.cpp, tools/packchk/test/data/schema.xsd, tools/packchk/test/integtests/CMakeLists.txt, tools/packchk/test/integtests/src/PackChkIntegTestEnv.cpp, tools/packchk/test/integtests/src/PackChkIntegTests.cpp
Signed-off-by: yvesll <toyears@hotmail.com>
**NOTE:
This PR did not include the mandatory option which moves PACK.xsd to <cmsis_toolbox>/etc, I do not know the deployment flow.**
=> [packchk] Add xml validation for input PDSCs (#506)

libs/rtemodel/include/RteProject.h, libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/RteCprjProject.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp, libs/rtemodel/test/src/RteChkTest.cpp, libs/rtemodel/test/src/RteModelTest.cpp, libs/rtemodel/test/src/RteModelTestConfig.cpp, libs/rtemodel/test/src/RteModelTestConfig.h, libs/rteutils/include/RteUtils.h, libs/rteutils/src/RteUtils.cpp, libs/rteutils/test/src/RteUtilsTest.cpp, libs/xmltree/src/XmlItem.cpp, test/packs/ARM/RteTestBoard/0.1.0/ARM.RteTestBoard.pdsc, test/projects/RteTestM4/RteTestM4_Board.cprj, test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h, test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h
* [csolution] Generate regions_*.h file from memory tags #739
=> [csolution] Generate regions_*.h file from memory tags #739 (#500)

libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/src/RteItem.cpp, libs/rtemodel/src/RteTarget.cpp, libs/xmltree/include/XMLTree.h, libs/xmltree/include/XmlTreeItem.h, libs/xmltree/src/XMLTree.cpp
* RTE Model refactoring
Fix bug introduced by removal of RteGeneratorModel class
Move some generic methods from XMLTreeElement to XmlTreeItem<>
=> RTE Model refactoring (#504)

tools/buildmgr/cbuildgen/CMakeLists.txt
- use cmake command to copy files
=> CMake: Rework system/arch handing (#506)

libs/rtemodel/src/RteInstance.cpp
=> Bugfix in calculating pack ID in RtePackageInstanceInfo (#508)

tools/packchk/src/CheckFiles.cpp
- MakePathCanonical() also for package path to test against
Relates to #800
=> [packchk] Error M313 reported: does not look very valid #800 (#509)

libs/rtefsutils/include/RteFsUtils.h, libs/rtefsutils/src/RteFsUtils.cpp, libs/rtefsutils/test/src/RteFsUtilsTest.cpp
=> RteFsUtils::CopyFileExAutoRetry

tools/svdconv/SVDConv/src/ProductInfo.h.in
https://github.com/Open-CMSIS-Pack/devtools/security/code-scanning/1452
=> Missing header guard (#512)

CMakeLists.txt
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html#variable:CMAKE_OSX_DEPLOYMENT_TARGET
Relates to Open-CMSIS-Pack/cmsis-toolbox#31
=> Specify minimum SDK version for MacOS to 11.7 Big Sur

tools/projmgr/schemas/cbuild.schema.json, tools/projmgr/schemas/cdefault.schema.json, tools/projmgr/schemas/clayer.schema.json, tools/projmgr/schemas/common.schema.json, tools/projmgr/schemas/cproject.schema.json, tools/projmgr/schemas/csolution.schema.json
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/813
=> Reduce number of characters in JSON schema title

libs/rtemodel/include/RteItem.h, libs/rtemodel/include/RteModel.h, libs/rtemodel/include/RtePackage.h, libs/rtemodel/src/RteComponent.cpp, libs/rtemodel/src/RteCprjProject.cpp, libs/rtemodel/src/RteItem.cpp, libs/rtemodel/src/RteModel.cpp, libs/rtemodel/src/RtePackage.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp, libs/rtemodel/test/src/RteModelTest.cpp, test/projects/RteTestM4/RteTestM4_Board.cprj, tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrUtils.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrUtils.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/TestProjectEnforcedComponent/TestProjectEnforcedComponent.cproject.yml, tools/projmgr/test/data/TestSolution/TestProjectEnforcedComponent/main.c, tools/projmgr/test/data/TestSolution/test.enforced_component.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrUtilsUnitTests.cpp
* enforced component selection using extended component identifier #774
=> enforced component selection using extended component identifier #774 (#516)

tools/projmgr/docs/Manual/YML-CBuild-Format.md, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Release+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/outputFiles.Debug+Target.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/outputFiles.Library+Target.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrTestEnv.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/652
=> [projmgr] Added generated-by node to generated yml files

libs/rtemodel/include/RteCondition.h, libs/rtemodel/src/RteCondition.cpp, libs/rtemodel/src/RteModel.cpp, libs/rtemodel/test/src/RteChkTest.cpp, libs/rtemodel/test/src/RteConditionTest.cpp, test/packs/ARM/RteTest/0.1.0/ARM.RteTest.pdsc
respect multiple choices via accept conditions
=> Component auto-resolve: (#531)

tools/projmgr/include/ProjMgrParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/LinkerOptions/linker.clayer.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/linker.cproject.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_AC6+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/833
=> [projmgr] Add support for specifying linker pre-processing `define`

tools/buildmgr/cbuild/include/CbuildModel.h, tools/buildmgr/cbuild/src/CbuildModel.cpp, tools/buildmgr/cbuildgen/config/CPRJ.xsd, tools/buildmgr/cbuildgen/include/BuildSystemGenerator.h, tools/buildmgr/cbuildgen/src/BuildSystemGenerator.cpp, tools/buildmgr/cbuildgen/src/CMakeListsGenerator.cpp, tools/buildmgr/test/integrationtests/src/CBuildGCCTests.cpp, tools/buildmgr/test/testinput/Examples/GCC/StandardLibrary/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/GCC/StandardLibrary/MyMain.c, tools/buildmgr/test/testinput/Examples/GCC/StandardLibrary/MyProject.cprj, tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/StandardLibrary/library.cproject.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/library.csolution.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/735
=> [buildmgr, projmgr] Add linker library flags handling

tools/projmgr/schemas/common.schema.json, tools/projmgr/test/src/ProjMgrSchemaCheckerUnitTests.cpp
Related to https://github.com/Open-CMSIS-Pack/devtools/issues/819
=> Extend schema with created-by, created-for & description fields (#537)

tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_AC6+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/library.cproject.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cprj, tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Release+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/778#issuecomment-1534702392
=> [projmgr] Add 'output' name and type to cbuild.yml

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild.yml
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/891
=> [projmgr] Update active RTE project name (#554)

libs/rtemodel/src/RteTarget.cpp
- check device for null pointer
- replaces dashes with underscores in protection define
=> Memory regions file: (#555)

libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/RteTarget.cpp, libs/rteutils/include/WildCards.h, libs/rteutils/src/VersionCmp.cpp, libs/rteutils/src/WildCards.cpp, libs/rteutils/test/src/RteUtilsTest.cpp, test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h, test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h
issues 1., 4. and partially 2.
=> Linker Script Management - small issues #901 (#558)

tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestDefault/ref/empty/empty.cbuild-idx.yml, tools/projmgr/test/data/TestDefault/ref/empty/project.Debug.cbuild.yml, tools/projmgr/test/data/TestDefault/ref/empty/project.Release.cbuild.yml, tools/projmgr/test/src/ProjMgrTestEnv.cpp, tools/projmgr/test/src/ProjMgrTestEnv.h, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/907
=> [projmgr] Fix cdefault/csolution reference format in cbuild-idx.yml

libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp, libs/rtemodel/test/src/RteModelTest.cpp, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/LinkerOptions/layer/linker.clayer.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/linker.cproject.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_AC6+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_AC6+RteTest_ARMCM3.cprj, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cprj, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.PriorityDefines+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.PriorityRegions+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/901
=> [projmgr] Refine regions header file generation triggering

libs/rtemodel/include/RteCondition.h, libs/rtemodel/include/RteItem.h, libs/rtemodel/src/RteCondition.cpp, libs/rtemodel/src/RteItem.cpp, libs/rtemodel/test/src/RteChkTest.cpp, libs/rtemodel/test/src/RteConditionTest.cpp, test/packs/ARM/RteTest/0.1.0/ARM.RteTest.pdsc
* Improvements in evaluating dependencies
Bugfix in deny dependency + tests
tracing of condition evaluation is added
=> Improvements in evaluating dependencies (#567)

tools/buildmgr/cbuildgen/config/GCC.10.3.1.cmake
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/914
=> [buildmgr] Group GCC libraries for rescanning

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/test2.Debug+CM3.cprj, tools/projmgr/test/data/TestSolution/ref/toolchains/toolchain.Debug+Target.cprj.ac6_6_16_1, tools/projmgr/test/data/TestSolution/ref/toolchains/toolchain.Debug+Target.cprj.ac6_6_20_0, tools/projmgr/test/data/TestSolution/ref/toolchains/toolchain.Debug+Target.cprj.ac6_6_6_5, tools/projmgr/test/data/TestSolution/ref/toolchains/toolchain.Debug+Target.cprj.gcc, tools/projmgr/test/data/TestSolution/ref/toolchains/toolchain.Debug+Target.cprj.iar, tools/projmgr/test/data/TestSolution/test.csolution.yml, tools/projmgr/test/data/TestSolution/test.csolution_validate_define_syntax.yml, tools/projmgr/test/data/TestSolution/toolchain-selection.csolution.yml, tools/projmgr/test/src/ProjMgrSchemaCheckerUnitTests.cpp
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/843
=> [projmgr] Change define syntax to standard key: value or string

cmake/ProjectVersionFromGitTag.cmake
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/928
=> [devtools] Support pre-release semantic version extension from git tag

libs/rtemodel/src/RteTarget.cpp, test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h, test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h
=> Linker Script Management - small issues #901 (#578)

tools/projmgr/include/ProjMgrGenerator.h, tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestProjectSetup/ref/setup-test.Build GCC.cprj, tools/projmgr/test/data/TestProjectSetup/setup-test.cproject.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/linker.cproject.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cprj, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Align `setup` handling with [specification](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#setups).
=> [projmgr] Add `linker` and `processor` nodes into `setup` handling

tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/727
=> [projmgr] Add `update-rte` command

tools/packchk/src/CreateModel.cpp, tools/packchk/src/PackChk.cpp, tools/packchk/src/PackChk_Msgs.cpp, tools/packchk/src/PackOptions.cpp, tools/packchk/test/integtests/src/PackChkIntegTests.cpp
* reviewed error messages
* fixed test cases
=> [packchk] reviewed error messages (#590)

libs/rtemodel/test/src/RteChkTest.cpp, libs/rtemodel/test/src/RteModelTest.cpp, test/packs/ARM/RteTest/0.1.0/ARM.RteTest.pdsc, test/projects/RteTestM3/RteTestM3.cprj, test/projects/RteTestM4/RteTestM4.cprj, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestProject/test_component_empty_variant_CM0.cproject.yml, tools/projmgr/test/data/TestProject/test_component_empty_variant_CM3.cproject.yml, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
* csolution does not use 'isDefaultVariant' of a component #740
* Warning does not indicate the cproject.yml file that is processed #967
---------
=> csolution does not use 'isDefaultVariant' of a component #740 (#598)

tools/buildmgr/cbuildgen/config/CMakeASM/ARMClang-AS_ARM.cmake, tools/buildmgr/cbuildgen/config/CMakeASM/ARMClang-AS_GNU.cmake, tools/buildmgr/cbuildgen/config/CMakeASM/ARMClang-AS_LEG.cmake, tools/buildmgr/cbuildgen/config/CMakeASM/CMakeAS_ARMCompiler.cmake.in, tools/buildmgr/cbuildgen/config/CMakeASM/CMakeAS_GNUCompiler.cmake.in, tools/buildmgr/cbuildgen/config/CMakeASM/CMakeAS_LEGCompiler.cmake.in
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/978
=> [buildmgr] Update CMakeASM files (#605)

test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc, tools/buildmgr/cbuild/src/CbuildModel.cpp, tools/buildmgr/cbuild/src/CbuildProject.cpp, tools/buildmgr/test/integrationtests/CMakeLists.txt, tools/buildmgr/test/integrationtests/src/CBuildGenTests.cpp, tools/buildmgr/test/testinput/Examples/Mixed/GpdscBundle/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/Mixed/GpdscBundle/MultipleComponents.cprj, tools/buildmgr/test/testinput/Examples/Mixed/GpdscBundle/MultipleComponents/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest.gpdsc, tools/buildmgr/test/testinput/Examples/Mixed/GpdscBundle/MultipleComponents/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest_Generated_Component1.c, tools/buildmgr/test/testinput/Examples/Mixed/GpdscBundle/MultipleComponents/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest_Generated_Component2.c, tools/buildmgr/test/testinput/Examples/Mixed/GpdscBundle/RTE/_Target_1/RTE_Components.h, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestGenerator/MultipleComponents/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest.gpdsc, tools/projmgr/test/data/TestGenerator/MultipleComponents/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest_Generated_Component1.c, tools/projmgr/test/data/TestGenerator/MultipleComponents/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest_Generated_Component2.c, tools/projmgr/test/data/TestGenerator/multiple-components.cproject.yml, tools/projmgr/test/data/TestGenerator/multiple-components.csolution.yml, tools/projmgr/test/data/TestGenerator/ref/multiple-components.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestGenerator/ref/multiple-components.Debug+CM0.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/961
=> [projmgr, buildmgr] Support GPDSC bundle

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestProjectSetup/ref/setup-test.Build AC6+TEST_TARGET.cprj, tools/projmgr/test/data/TestProjectSetup/ref/setup-test.Build GCC+TEST_TARGET.cprj, tools/projmgr/test/data/TestProjectSetup/setup-test.cproject.yml
Support multiple setups for each context.
Update yml schema and test cases.
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/973 and https://github.com/Open-CMSIS-Pack/devtools/issues/970.
=> [projmgr] Update `setup` handling

tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing https://github.com/Open-CMSIS-Pack/devtools/issues/825
=> [projmgr] Validation test for relax ordered context i.e project+targettype.buildtype

tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrYamlParser.cpp
Fixes https://github.com/Open-CMSIS-Pack/devtools/issues/999
=> [projmgr] Accept solution `description` node in parser validation

libs/rtemodel/test/src/RteChkTest.cpp
Fixes Open-CMSIS-Pack/devtools#1002
=> Fix RteChkTest.Summary after increasing components.

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/templates/cdefault.yml, tools/projmgr/test/data/TestSolution/toolchain-redefinition.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Fixes https://github.com/Open-CMSIS-Pack/devtools/issues/1004
Set GCC as default compiler selection in `cdefault.yml`.
=> [projmgr] Accept command line toolchain redefinition

tools/buildmgr/cbuild/src/CbuildProject.cpp, tools/buildmgr/cbuildgen/config/CPRJ.xsd, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrTestEnv.cpp
https://github.com/Open-CMSIS-Pack/devtools/issues/1001
=> Complement AC5 support removal

libs/rtemodel/src/RteInstance.cpp
=> MDK: fix reading pack filter from uvprojx (#627)

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/1029
=> [projmgr] Accept default linker script from different drive

.devcontainer/debian-10/Dockerfile, .devcontainer/debian-10/devcontainer.json, .devcontainer/ubuntu-20.04/Dockerfile, .devcontainer/ubuntu-20.04/devcontainer.json, .devcontainer/ubuntu-22.04/Dockerfile, .devcontainer/ubuntu-22.04/devcontainer.json, README.md
=> Provide VSCode Dev Container for Linux development

libs/rtefsutils/src/RteFsUtils.cpp, libs/rtefsutils/test/src/RteFsUtilsTest.cpp
[security] To permissive permissions set in RteFsUtils functions #1006
=> [security] Too permissive permissions set in RteFsUtils functions #1006 (#647)

libs/rteutils/CMakeLists.txt, libs/rteutils/include/RteConstants.h, libs/rteutils/src/RteUtils.cpp, tools/projmgr/include/ProjMgrUtils.h, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrUtils.cpp, tools/projmgr/src/ProjMgrWorker.cpp
=> Introduce RteConstants.h (#651)

libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp
* Save the original pack info for bootstrap components
=>  Save the original pack info for bootstrap components  (#652)

libs/rtemodel/src/RteComponent.cpp
=> Correct display name for API (#654)

CMakeLists.txt, external/yaml-cpp.patch, tools/projmgr/test/data/TestSolution/non-unique-map-keys.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
[yaml-cpp] Update external submodule to version 0.8.0
[yaml-cpp, projmgr] Validate map key uniqueness
[yaml-cpp] Fix ampersand identification as anchor
Adress https://github.com/Open-CMSIS-Pack/devtools/issues/927
=> [yaml-cpp, projmgr] Validate map key uniqueness

tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/pack_path.csolution.yml, tools/projmgr/test/data/TestSolution/pack_path_invalid.csolution.yml, tools/projmgr/test/data/TestSolution/test_local_pack_file_not_found.csolution.yml, tools/projmgr/test/data/TestSolution/test_local_pack_path.csolution.yml, tools/projmgr/test/data/TestSolution/test_local_pack_path_not_found.csolution.yml, tools/projmgr/test/data/Validation/recursive.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1097
=> [projmgr] Forbid version for pack selection with `path` specified

libs/rtemodel/include/RteInstance.h, libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/test/src/RteConditionTest.cpp
improved error reporting for tools
=> [RTE] API version selection/resolution may be incorrect #1124 (#692)

libs/ymltree/CMakeLists.txt
=> Remove ErrLog from YmlTree dependencies (#699)

tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlEmitter.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/include/ProjMgrYamlSchemaChecker.h, tools/projmgr/schemas/cbuildset.schema.json, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrParser.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/src/ProjMgrYamlSchemaChecker.cpp, tools/projmgr/test/CMakeLists.txt, tools/projmgr/test/data/TestSolution/invalid_keys_test.cbuild-set.yml, tools/projmgr/test/data/TestSolution/invalid_test.cbuild-set.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/all_contexts_test.cbuild-set.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/all_contexts_test_with_AC6.cbuild-set.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/specific_contexts_test.cbuild-set.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/specific_contexts_test_without_toolchain.cbuild-set.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp, tools/projmgr/test/src/ProjMgrYamlParserUnitTest.cpp
Addressing https://github.com/Open-CMSIS-Pack/devtools/issues/1127
=> [projmgr] Generate *.cbuild-set.yml listing selected contexts

tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/DeviceAttributes/branch-protection/branch-protection.cproject.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/branch-protection/bti-signret.clayer.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/branch-protection/bti.clayer.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/branch-protection/no-bp.clayer.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/ref/branch-protection.Debug+bti-signret.cbuild.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/ref/branch-protection.Debug+bti.cbuild.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/ref/branch-protection.Debug+no-bp.cbuild.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/solution.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1069
=> [projmgr] Add support for branch protection (PACBTI)

.github/codeql-config.yml, .github/workflows/codeql-analysis.yml
- Added job concurrency check
- CodeQL configurations to exclude directories
=> Update codeQL configurations

tools/projmgr/include/ProjMgrUtils.h
Address https://github.com/Open-CMSIS-Pack/devtools/security/code-scanning/3505
=> [projmgr] Fix CodeQL warning

tools/projmgr/include/ProjMgr.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/novalid_context.csolution.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/all_contexts_test_with_AC6.cbuild-set.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/specific_contexts_test_AC6.cbuild-set.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
https://github.com/Open-CMSIS-Pack/devtools/issues/1173
* [projmgr] Add -S,--context-set option
* Addressed review comments
=> [projmgr] Implemented -S,--context-set option

tools/projmgr/schemas/common.schema.json, tools/projmgr/test/data/TestProject/incomplete_output_type.cproject.yml, tools/projmgr/test/src/ProjMgrSchemaCheckerUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1152
=> [csolution] fixed output type schema misalignment

.github/workflows/cpp-linter.yml
=> Link to the report on the repo that ran the action

libs/rtemodel/include/RteItem.h, libs/rtemodel/include/RteKernel.h, libs/rtemodel/include/RteModel.h, libs/rtemodel/include/RtePackage.h, libs/rtemodel/src/RteDevice.cpp, libs/rtemodel/src/RteKernel.cpp, libs/rtemodel/src/RteModel.cpp, libs/rtemodel/src/RtePackage.cpp, libs/rteutils/CMakeLists.txt, libs/rteutils/include/CollectionUtils.h, libs/rteutils/include/RteUtils.h, libs/rteutils/test/src/RteUtilsTest.cpp, tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrUtils.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestSolution/Packs/RteTestRequired/ARM.RteTestRequired.pdsc, tools/projmgr/test/data/TestSolution/Packs/RteTestRequired1/ARM.RteTestRequired.pdsc, tools/projmgr/test/data/TestSolution/test_pack_path.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Implements [csolution] A pack: specified with path: in YAML input takes precedence over the regularly installed pack version #1098
=> A pack specified with path should take precedence

tools/projmgr/schemas/common.schema.json
Addresses https://github.com/Open-CMSIS-Pack/devtools/issues/1267
=> [projmgr] Re-add enum value to cbuild schema for backward compatibility

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp
Address "Generator run information" part of https://github.com/Open-CMSIS-Pack/devtools/issues/1265#issuecomment-1898010615
=> [projmgr] Create `cbuild.yml` regardless of `convert` call's outcome

libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/RteComponent.cpp, libs/rtemodel/src/RteTarget.cpp
use only bundles with at least one filtered component
=> Filter component bundles

libs/rteutils/include/CollectionUtils.h, libs/rteutils/include/RteUtils.h, libs/rteutils/src/CollectionUtils.cpp, libs/rteutils/src/RteUtils.cpp, libs/rteutils/test/src/RteUtilsTest.cpp, tools/buildmgr/cbuild/include/CbuildModel.h, tools/buildmgr/cbuild/src/CbuildLayer.cpp, tools/buildmgr/cbuild/src/CbuildModel.cpp, tools/buildmgr/test/unittests/src/CLayerTests.cpp, tools/buildmgr/test/unittests/src/CbuildModelTests.cpp, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
make some common code accessible from different tools
remove duplicates
=> Support for external generators in RTE Model (continue)

tools/projmgr/schemas/common.schema.json
Fixes https://github.com/Open-CMSIS-Pack/devtools/issues/1327
=> [projmgr] Update schema for accepting empty groups in cbuild.yml files

tools/projmgr/schemas/common.schema.json
Fixes https://github.com/Arm-Debug/uvprojx-converter/issues/235
=> [projmgr] Update schema: accept non-unique defines in *.cbuild.yml (#800)

tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrGenerator.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/Instances/instances.cproject.yml, tools/projmgr/test/data/TestSolution/Instances/instances.csolution.yml, tools/projmgr/test/data/TestSolution/Instances/ref/instances.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/Instances/ref/instances.Debug+RteTest_ARMCM3.cprj, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Fixes https://github.com/Open-CMSIS-Pack/devtools/issues/1123
=> [projmgr] Support multiple component instances

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Fix for issue #1356
unclear warning csolution: required pack 'ARM::CMSIS-Compiler@2.0.0' is not loaded #1356
* Apply suggestions from code review
---------
=> Fix for issue #1356

.github/workflows/test_libs.yml, libs/rtemodel/test/src/RteChkTest.cpp, test/packs/ARM/RteTest/0.1.0/API/IConfig.h, test/packs/ARM/RteTest/0.1.0/ARM.RteTest.pdsc, test/packs/ARM/RteTest/0.1.0/Template/template.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestSolution/TemplateAndApi/ref/template_api.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/TemplateAndApi/template_api.cproject.yml, tools/projmgr/test/data/TestSolution/TemplateAndApi/template_api.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing part of https://github.com/Open-CMSIS-Pack/devtools/issues/1322
=> <context>.cbuild.yml extension properties (#822)

libs/rtemodel/src/RteGenerator.cpp, libs/rtemodel/src/RteInstance.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/test/src/RteModelTest.cpp
* Support for external generators in RTE Model (multi-core)
=> Support for external generators in RTE Model (multi-core)

tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/PackLocking/selected-by.cbuild-pack.yml, tools/projmgr/test/data/TestSolution/PackLocking/selected-by.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1402
=> [projmgr] Accept `select-by` in *.cbuild-pack.yml for backward compatibility

tools/projmgr/schemas/common.schema.json, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address fundamental problem (missing `cdefault`) of https://github.com/Open-CMSIS-Pack/devtools/issues/1397
=> [projmgr] Add `cdefault` to *.cbuild-idx.yml schema

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
use GetEffectivePdscFile() in ProjMgrWorker::AddPackRequirements()
=> [projmgr] csolution usage of local_repository.pidx packs #1430 (pack req)

libs/rtemodel/test/src/RteModelTest.cpp
split PackRegistry test
add additional assertions and checks
=> PackRegistry tests improvements

tools/buildmgr/cbuild/src/CbuildModel.cpp, tools/buildmgr/test/integrationtests/src/CBuildTestFixture.cpp, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File1.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File2.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File3.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File4.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/Project.cprj, tools/buildmgr/test/testinput/Examples/GCC/NestedGroups/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/GCC/NestedGroups/File1.c, tools/buildmgr/test/testinput/Examples/GCC/NestedGroups/File2.c, tools/buildmgr/test/testinput/Examples/GCC/NestedGroups/File3.c, tools/buildmgr/test/testinput/Examples/GCC/NestedGroups/File4.c, tools/buildmgr/test/testinput/Examples/GCC/NestedGroups/Project.cprj
Improved defines list calculation to only exact key match
=> Improved defines list calculation to only match key

tools/buildmgr/cbuildgen/src/CMakeListsGenerator.cpp, tools/buildmgr/test/testinput/Examples/GCC/TranslationControl/Project1/CMakeLists.txt.ref
Address https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/119
=> [buildmgr] Fix missing CXX file flag

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1174
=> [projmgr] Relax single context requirement for running global generators

tools/projmgr/src/ProjMgr.cpp, tools/projmgr/test/data/ExternalGenerator/extgen.cbuild-set.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1463
=> [projmgr] Support `--context-set` option in `run` command

tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences2.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/ref/config.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/ref/select.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/ref/variables/variables.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1414
=> [projmgr] Add `clayers` for each `cbuild` context

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/ExternalGenerator/board.csolution.yml, tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+Board.cbuild.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1510
=> [projmgr] Fix missing device info due to generator import file processing

libs/rtemodel/include/RteModel.h, libs/rtemodel/include/RtePackage.h, libs/rtemodel/src/RteModel.cpp, test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, test/packs/ARM/RteTest_DFP/0.2.0/Templates/board1.csolution.yml, test/packs/ARM/RteTest_DFP/0.2.0/Templates/board2.csolution.yml, test/packs/ARM/RteTest_DFP/0.2.0/Templates/board3.csolution.yml
* [RteModel] Improve support for csolution pdsc element
processing clayer and template elements
remove unused code
=> [RteModel] Improve support for csolution pdsc element

tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/CMakeLists.txt.ref, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File1.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File2.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File3.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/File4.c, tools/buildmgr/test/testinput/Examples/AC6/NestedGroups/Project.cprj
=> Updated test example

tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake
Implementation aligned with other cmake files.
@fred-r @tarek-bochkati
=> Update IAR.9.32.1.cmake for Secure

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/ref/variables-notdefined.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1537
=> [projmgr] List layers: update `*.cbuild.yml` also in case of errors

tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrParser.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/Executes/error.csolution.yml, tools/projmgr/test/data/TestSolution/Executes/solution.csolution.yml, tools/projmgr/test/data/TestSolution/created-for.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1536
=> [projmgr] Check `created-for:` with version number

tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1538
=> [projmgr] Throw warning in case `board` or `device` name are set in *.cproject.yml or *.clayer.yml

libs/rtemodel/include/RteFile.h, libs/rtemodel/src/RteFile.cpp, libs/rtemodel/src/RteProject.cpp, libs/rtemodel/src/RteTarget.cpp, libs/rtemodel/src/RteValueAdjuster.cpp, tools/projmgr/test/data/TestSolution/LanguageAndScope/ref/lang-scope.Debug_AC6+RteTest_ARMCM3.cbuild.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1369
Spec: https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_components_pg.html#FileScopeAttributeType
=> [rtemodel] Unify file `scope` attribute

tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlEmitter.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestSolution/SelectableToolchains/cdefault.yml, tools/projmgr/test/data/TestSolution/SelectableToolchains/ref/select-compiler.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/SelectableToolchains/select-compiler.cproject.yml, tools/projmgr/test/data/TestSolution/SelectableToolchains/select-compiler.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1569 and https://github.com/Open-CMSIS-Pack/devtools/issues/1576
=> [projmgr] Handle `select-compiler` info when compiler is not defined

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/ComponentSources/components.cproject.yml, tools/projmgr/test/data/TestSolution/ComponentSources/components.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1572
=> [projmgr] Validate component sources

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cprj, tools/projmgr/test/data/TestSolution/ref/outputFiles.Library+Target.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/outputFiles.Library+Target.cprj
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1133
=> [projmgr] Skip emitting linker options for library targets

tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1573
=> [projmgr] Add `--cbuild2cmake` option

tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/data/TestLayers/ref/variables-notdefined.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/variables-notdefined.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1562
=> [projmgr] cbuild setup --context-set should execute first project

tools/projmgr/schemas/common.schema.json
Remove output-dirs from cproject.yml schema
=> Remove "output-dirs" from cproject.yml schema

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1590 and https://github.com/Open-CMSIS-Pack/devtools/issues/1594
=> [projmgr] Improve error/warning messages

tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1598
=> [projmgr] Rework warning message for device/board deprecation (#953)

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestSolution/RebuildConditions/rebuild.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/RebuildConditions/rebuild.cproject.yml, tools/projmgr/test/data/TestSolution/RebuildConditions/rebuild.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address `csolution` part of https://github.com/Open-CMSIS-Pack/devtools/issues/1592
=> [projmgr] Set `rebuild` flag in `cbuild-idx.yml`

tools/projmgr/src/ProjMgr.cpp, tools/projmgr/test/data/TestSolution/PackMissing/ref/missing_pack_specific_context.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/TestProject1/ref/test_no_device_name.cbuild-idx.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1426
=> [projmgr] List only selected contexts in build index

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/test_use_multiple_variant_component.cproject.yml, tools/projmgr/test/data/TestSolution/test_use_multiple_variant_component.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Error on use of multiple variants of the same component for the same context
* check for multiple component variants
=> Error on use of multiple variants of the same component for the same context (#960)

tools/projmgr/src/ProjMgrWorker.cpp
Error message udpate with correct toolchain name
=> Error message update with correct toolchain name (#961)

libs/rtemodel/src/RteProject.cpp, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-project-files.Debug+CM0.cbuild.yml
* Ensure generator from gpdsc is used if available
* Ensure generator from gpdsc is used if available
Update test
=> Ensure generator from gpdsc is used if available

tools/projmgr/src/ProjMgr.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1612
=> [projmgr] Updated usage with -O option

libs/rtemodel/test/src/RteModelTest.cpp, test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, test/packs/ARM/RteTest_DFP/0.2.0/Layers/config3.clayer.yml, tools/projmgr/include/ProjMgrUtils.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/ref/config.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrTestEnv.cpp, tools/projmgr/test/src/ProjMgrTestEnv.h, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Addresses https://github.com/Open-CMSIS-Pack/devtools/issues/1614
=> [projmgr] List layers: fix connections `set` combinations

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/empty-layer.cproject.yml, tools/projmgr/test/data/TestLayers/empty-layer.csolution.yml, tools/projmgr/test/data/TestLayers/ref/empty-layer.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1620
=> [projmgr] Ignore `layer` entry expanded to empty string

tools/projmgr/src/ProjMgr.cpp, tools/projmgr/test/data/TestSolution/ref/cbuild/first_build_target.cbuild.set.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1634
=> [projmgr] update cbuild-set.yml according to context selection

tools/projmgr/src/ProjMgr.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/1655
=> [projmgr] Improved error message

libs/rtemodel/src/RteTarget.cpp, test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h, test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest-Test-board_With.Memory.h, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest_ARMCM3.h
Adressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1670
=> avoid special characters in regions.h confusing config wizard parsing

tools/projmgr/schemas/common.schema.json
Addressing:https://github.com/Open-CMSIS-Pack/devtools/issues/1561
This change was constructed by search-replace on this file:
[\\w-] -> [a-zA-Z0-9_]
[\\d] -> [0-9]
=> Use of expanded regex notations (#999)

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestLayers/no_compiler.cproject.yml, tools/projmgr/test/data/TestLayers/no_compiler.csolution.yml, tools/projmgr/test/data/TestLayers/ref/no_compiler.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1663
=> cbuild setup delivering missing info when no compiler specified (#1002)

tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/BaseUnknown/Device/RteTest_ARMCM3/ARMCM3_ac6.sct, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/BaseUnknown/Device/RteTest_ARMCM3/startup_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/BaseUnknown/Device/RteTest_ARMCM3/system_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Major/Device/RteTest_ARMCM3/ARMCM3_ac6.sct, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Major/Device/RteTest_ARMCM3/ARMCM3_ac6.sct.base@1.2.0, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Major/Device/RteTest_ARMCM3/startup_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Major/Device/RteTest_ARMCM3/startup_ARMCM3.c.base@3.0.0, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Major/Device/RteTest_ARMCM3/system_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Major/Device/RteTest_ARMCM3/system_ARMCM3.c.base@1.2.2, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Minor/Device/RteTest_ARMCM3/ARMCM3_ac6.sct, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Minor/Device/RteTest_ARMCM3/ARMCM3_ac6.sct.base@1.2.0, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Minor/Device/RteTest_ARMCM3/startup_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Minor/Device/RteTest_ARMCM3/startup_ARMCM3.c.base@2.1.0, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Minor/Device/RteTest_ARMCM3/system_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Minor/Device/RteTest_ARMCM3/system_ARMCM3.c.base@1.2.2, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Patch/Device/RteTest_ARMCM3/ARMCM3_ac6.sct, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Patch/Device/RteTest_ARMCM3/ARMCM3_ac6.sct.base@1.2.0, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Patch/Device/RteTest_ARMCM3/startup_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Patch/Device/RteTest_ARMCM3/startup_ARMCM3.c.base@2.0.0, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Patch/Device/RteTest_ARMCM3/system_ARMCM3.c, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/Patch/Device/RteTest_ARMCM3/system_ARMCM3.c.base@1.2.2, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/config.cproject.yml, tools/projmgr/test/data/TestSolution/ConfigFilesUpdate/config.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1694
=> [projmgr] Check config files existence and versions (#1006)

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/Instances/ref/instances.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/TestBaseUpdate/ref/project.Debug+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1694
=> [projmgr] Add PLM status into config file nodes in cbuild.yml (#1007)

libs/rteutils/include/RteConstants.h, libs/rteutils/src/RteConstants.cpp, tools/buildmgr/cbuildgen/config/AC6.6.16.2.cmake, tools/buildmgr/cbuildgen/config/CLANG.17.0.1.cmake, tools/buildmgr/cbuildgen/config/GCC.10.3.1.cmake, tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake, tools/projmgr/schemas/common.schema.json, tools/projmgr/test/data/TestSolution/DeviceAttributes/ref/trustzone.Debug+secure-only.cbuild.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/ref/trustzone.Debug+secure-only.cprj, tools/projmgr/test/data/TestSolution/DeviceAttributes/solution.csolution.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/trustzone/secure-only.clayer.yml, tools/projmgr/test/data/TestSolution/DeviceAttributes/trustzone/trustzone.cproject.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1711
Aligned with https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/pull/323
=> [devtools] Add support for trustzone mode `secure-only`

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestSolution/LinkerOptions/linker.cproject.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1721
=> [projmgr] Generate warning when linker script files are ignored (#1013)

libs/rtemodel/include/RteTarget.h, libs/rtemodel/src/RteTarget.cpp, test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h, tools/projmgr/test/data/TestMemoryRegions/pack/BSP/ARM.RteTest_BSP.pdsc, tools/projmgr/test/data/TestMemoryRegions/pack/DFP/ARM.RteTest_DFP.pdsc, tools/projmgr/test/data/TestMemoryRegions/ref/RteTestDevice0/regions_RteTestBoard0.h, tools/projmgr/test/data/TestMemoryRegions/ref/RteTestDevice1/regions_RteTestBoard1.h, tools/projmgr/test/data/TestMemoryRegions/ref/RteTestDevice_Dual_cm0_core1/regions_RteTestDevice_Dual_cm0_core1.h, tools/projmgr/test/data/TestMemoryRegions/regions.cproject.yml, tools/projmgr/test/data/TestMemoryRegions/regions.csolution.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest-Test-board_With.Memory.h, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest_ARMCM3.h, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1718
=> [rtemodel, projmgr] Update memory `regions` header generation (#1015)

tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestLayers/config.cproject.yml, tools/projmgr/test/data/TestLayers/ref/config.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1620#issuecomment-2334163478
=> [projmgr] `list layers`: add discarded optional layer types into cbuild-idx.yml (#1017)

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/ComponentSources/ref/components.Debug+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1683#issuecomment-2338459137
=> [projmgr] Ignore duplicated component sources (#1022)

tools/projmgr/include/ProjMgrLogger.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrExtGenerator.cpp, tools/projmgr/src/ProjMgrLogger.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/src/ProjMgrYamlSchemaChecker.cpp, tools/projmgr/test/data/TestAccessSequences/ref/pack-access-sequences.cbuild-idx.yml, tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences2.cbuild-idx.yml, tools/projmgr/test/data/TestDefault/ref/empty/empty.cbuild-idx.yml, tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/ref/empty-layer.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/ref/variables-notdefined.cbuild-idx.yml, tools/projmgr/test/data/TestLayers/ref/variables/variables.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/Executes/ref/solution.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/PackMissing/ref/missing_pack.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/PackMissing/ref/missing_pack_specific_context.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/SelectableToolchains/ref/select-compiler.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/TestProject1/ref/test_no_device_name.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/ref/cbuild/test.cbuild-idx.yml, tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml, tools/projmgr/test/data/TestSolution/ref/pre-include.cbuild-idx.yml, tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1469
=> [projmgr] Rework logger: report error/warning/info messages in `cbuild-idx.yml` (#1024)

tools/projmgr/src/ProjMgrWorker.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1739
=> [projmgr] Fix user variables check order (#1028)

tools/projmgr/src/ProjMgr.cpp, tools/projmgr/test/data/TestLayers/ref/variables-notdefined.cbuild-idx.yml
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1792
=> Context specific error listing

tools/projmgr/src/ProjMgrWorker.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1812#issuecomment-2419266659
=> [projmgr] Global generator `run`: fix sibling contexts selection

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/src/ProjMgrYamlEmitter.cpp, tools/projmgr/test/data/TestAccessSequences/pack-access-sequences.csolution.yml, tools/projmgr/test/data/TestAccessSequences/ref/pack-access-sequences+CM4-Board.cbuild.yml, tools/projmgr/test/data/TestSolution/PacksUnused/packs.csolution.yml, tools/projmgr/test/data/TestSolution/PacksUnused/project.cproject.yml, tools/projmgr/test/data/TestSolution/SelectableToolchains/select-compiler.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1771
=> [projmgr] Collect and report `packs-unused` for each selected context

libs/rtefsutils/src/RteFsUtils.cpp, tools/projmgr/test/data/TestSolution/pack_case_sensitive.csolution.yml, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1262
=> [projmgr] Check pack identifier case consistency

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestSolution/LinkerOptions/layer/linker.clayer.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cprj, tools/projmgr/test/src/ProjMgrUnitTests.cpp, tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1814
=> [projmgr] Increase severity of missing specified regions header and unknown access sequence warnings

tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Debug+CM0.cprj, tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Release+CM0.cprj, tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences2.Debug+CM0.cprj, tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences2.Release+CM0.cprj, tools/projmgr/test/data/TestAccessSequences/test-access-sequences.csolution.yml
Address https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/205 and https://github.com/Open-CMSIS-Pack/devtools/issues/1846
=> [projmgr] Fix `$Bname$` access sequence expansion

tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/src/ProjMgrWorker.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1890
=> [projmgr] Layer detection: skip `device` requirement if `board` is already loaded

tools/projmgr/include/ProjMgr.h, tools/projmgr/src/ProjMgr.cpp
Address effect of https://github.com/Open-CMSIS-Pack/devtools/issues/1906 on csolution.
=> [projmgr] Skip writing `cbuild-run` in case of configuration errors

libs/rtefsutils/src/RteFsUtils.cpp, libs/rtemodel/src/RteModel.cpp, tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/269
=> [projmgr] Decrease pack letter case inconsistency severity

tools/projmgr/src/ProjMgr.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1917
=> Updated usage text for --output option (#1128)

tools/packchk/include/ValidateSyntax.h, tools/packchk/src/PackChk_Msgs.cpp, tools/packchk/src/ValidateSyntax.cpp, tools/packchk/test/data/TestLicense/TestVendor.TestPackLicense.pdsc, tools/packchk/test/data/TestLicense/licenses/license1.txt, tools/packchk/test/data/TestLicense/licenses/license2.txt, tools/packchk/test/data/TestLicense/licenses/myProprietaryLicense.txt, tools/packchk/test/integtests/src/PackChkIntegTests.cpp
* [packchk] Add a validation step issuing a warning in case no license information is contained in a pack #1304
=> [packchk] Add a validation step issuing a warning in case no license information is contained in a pack #1304 (#1149)

tools/packchk/src/PackChk_Msgs.cpp, tools/packchk/src/ValidateSyntax.cpp, tools/packchk/test/data/RteTestBoard/ARM.RteTestBoard.pdsc, tools/packchk/test/data/RteTestBoard/Board/Flash/BoardAlgo1.FLM, tools/packchk/test/data/RteTestBoard/Board/Flash/BoardAlgo2.FLM, tools/packchk/test/data/RteTestBoard/Documents/README.md, tools/packchk/test/integtests/src/PackChkIntegTests.cpp
* [packchk] issue warning for explicit include paths in *.pdsc to config files #1644
=> [packchk] Validate <mountedDevice> specifying an existing device #1079

tools/svdconv/SVDModel/include/SvdRegister.h, tools/svdconv/SVDModel/src/SvdRegister.cpp, tools/svdconv/Test/data/ResetMask/ResetMask.svd, tools/svdconv/Test/integtests/src/SvdConvIntegTests.cpp
* [svdconv] Wrong error message: *** ERROR M382:  #1264
* changed to uint
* fixed check for 64 bit wide register
* added test
=> Error M382vs64bit 1264 (#1177)

tools/projmgr/src/ProjMgrCbuildGenIdx.cpp, tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/extgen.cbuild-gen-idx.yml, tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/extgen.cbuild-gen-idx.yml, tools/projmgr/test/data/ExternalGenerator/ref/TrustZone/extgen.cbuild-gen-idx.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1930#issuecomment-2721127965
=> [cbuild-gen-idx.yml] Always output fully qualified device and board identifier

test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc, tools/projmgr/src/ProjMgrCbuildRun.cpp, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW2.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2053
=> [cbuild-run] Fix missing debug sequences

tools/projmgr/include/ProjMgrRunDebug.h, tools/projmgr/src/ProjMgrCbuildRun.cpp, tools/projmgr/src/ProjMgrRunDebug.cpp, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml
Address https://github.com/Open-CMSIS-Pack/cmsis-toolbox/pull/340/commits/390f8790d7ffec1020b52f6f429c2a48cb47c7e0
=> [cbuild-run] Remove default debugger `protocol` and `clock`

tools/projmgr/include/ProjMgr.h, tools/projmgr/include/ProjMgrParser.h, tools/projmgr/include/ProjMgrRunDebug.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/include/ProjMgrYamlParser.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/schemas/debug-adapters.schema.json, tools/projmgr/src/ProjMgr.cpp, tools/projmgr/src/ProjMgrCbuild.cpp, tools/projmgr/src/ProjMgrCbuildRun.cpp, tools/projmgr/src/ProjMgrParser.cpp, tools/projmgr/src/ProjMgrRunDebug.cpp, tools/projmgr/src/ProjMgrYamlParser.cpp, tools/projmgr/templates/debug-adapters.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW.cbuild.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW2.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW2.cbuild.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/run-debug.csolution.yml, tools/projmgr/test/src/ProjMgrTestEnv.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2056
Complementary to https://github.com/Open-CMSIS-Pack/devtools/pull/2063
=> [projmgr] Implement `debug-adapters.yml` handling

libs/rtemodel/src/RteTarget.cpp, test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h, test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h, tools/projmgr/test/data/TestMemoryRegions/ref/RteTestDevice1/regions_RteTestBoard1.h, tools/projmgr/test/data/TestMemoryRegions/ref/RteTestDevice_Dual_cm0_core1/regions_RteTestDevice_Dual_cm0_core1.h, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest-Test-board_With.Memory.h, tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest_ARMCM3.h
addressing https://github.com/Open-CMSIS-Pack/devtools/issues/2068
=> Update RteTarget.cpp using 0x0 instead of 0

tools/projmgr/include/ProjMgrRunDebug.h, tools/projmgr/include/ProjMgrWorker.h, tools/projmgr/schemas/common.schema.json, tools/projmgr/src/ProjMgrCbuildRun.cpp, tools/projmgr/src/ProjMgrRunDebug.cpp, tools/projmgr/src/ProjMgrWorker.cpp, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW.cbuild.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW2.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW2.cbuild.yml, tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml, tools/projmgr/test/data/TestRunDebug/run-debug.cproject.yml, tools/projmgr/test/data/TestRunDebug/run-debug.csolution.yml
Address changes documented in https://github.com/Open-CMSIS-Pack/cmsis-toolbox/pull/350
=> [cbuild-run] Debugger integration refinements

.github/workflows/projmgr.yml
Fixed the python version to 3.13.3 as the version (3.13.4) used by github runner has issues
https://github.com/python/cpython/issues/133779
=> Use fixed version of python (#1241)

tools/buildmgr/cbuildgen/config/AC6.6.16.2.cmake, tools/buildmgr/cbuildgen/config/CLANG.17.0.1.cmake, tools/buildmgr/cbuildgen/config/CLANG_TI.4.0.1.cmake, tools/buildmgr/cbuildgen/config/GCC.10.3.1.cmake, tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake
=> fix map file with space in path for GCC

tools/buildmgr/cbuildgen/config/AC6.6.16.2.cmake
[buildmgr] Add ASM flags for dependency rules generation
=> [buildmgr] Add AC6 ASM flags for dependency rules generation (#1265)

tools/projmgr/templates/cdefault.yml
Fixes Open-CMSIS-Pack/devtools#2147
=> Add flag -e to cdefault for IAR toolchain Fixes #2147

tools/projmgr/templates/clang_linker_script.ld.src
Adresses Open-CMSIS-Pack/devtools#2213
=> [projmgr] Enhance LLVM/clang linker script for compatibility with ATfE 21
