- tools/packgen/include/PackGen.h
- tools/packgen/src/PackGen.cpp
- tools/packgen/test/data/CMakeTestProject/invalid_manifest2.yml
- tools/packgen/test/src/PackGenUnitTests.cpp
- return an error when 'packs' mandatory section is missing
- return a warning when multiple 'components' sections are defined
- print all packchk results, including errors and warnings
- avoid calling CMake when no components are defined and verbose mode is disabled
> packgen: update errors/warnings handling

- test/packs/ARM/RteTest/0.1.0/ARM.RteTest.pdsc
- tools/packgen/docs/README.md
- tools/packgen/src/PackGen.cpp
The `PackChk` utility that is currently available is written in camel case:
https://github.com/ARM-software/CMSIS_5/tree/master/CMSIS/Utilities/
I suggest to revert the PR #12 now and remerge it when `packchk` will be released only with lower case characters.
> Revert "Packgen update parent"

- CMakeLists.txt
- libs/crossplatform/CMakeLists.txt
- libs/crossplatform/test/CMakeLists.txt
- libs/errlog/CMakeLists.txt
- libs/errlog/test/CMakeLists.txt
- libs/rtefsutils/CMakeLists.txt
- libs/rtefsutils/test/CMakeLists.txt
- libs/rtemodel/CMakeLists.txt
- libs/rtemodel/test/CMakeLists.txt
- libs/rteutils/CMakeLists.txt
- libs/rteutils/test/CMakeLists.txt
- libs/xmlreader/CMakeLists.txt
- libs/xmlreader/test/CMakeLists.txt
- libs/xmltree/CMakeLists.txt
- libs/xmltree/test/CMakeLists.txt
- libs/xmltreeslim/CMakeLists.txt
- libs/xmltreeslim/test/CMakeLists.txt
- tools/buildmgr/CMakeLists.txt
- tools/buildmgr/cbuild/CMakeLists.txt
- tools/buildmgr/cbuildgen/CMakeLists.txt
- tools/buildmgr/test/integrationtests/CMakeLists.txt
- tools/buildmgr/test/unittests/CMakeLists.txt
- tools/packgen/CMakeLists.txt
As mentioned in [documentation ](https://github.com/Open-CMSIS-Pack/devtools/blob/main/README.md) min version required is 3.18
- Updated min version from 3.14 to 3.18
- Deleted min version from all children CMakeLists.txt and use cmake_minimum_required from parent
> Updating cmake_minimum_required version from 3.14 to 3.18 (#31)

- tools/packgen/docs/README.md
- tools/packgen/src/PackGen.cpp
- tools/packgen/test/data/TestProject/lib1/CMakeLists.txt
Avoid adding a directory as a source file into a pack component.
Extend test case.
Update documentation using inclusive language.
> [packgen] Update CMake target's sources handling

- CMakeLists.txt
- README.md
- cmake/GetCMakeTargets.cmake
Currently, we are listing all the CMake targets in README.md file. Any new addition of targets or changing names of targets would need a change in the README.md. With these changes, we don't need to maintain any target list. The list will be created on the fly and users can open the list with a simple command. The generated list should look like:
`$ cat./targets`
> list all cmake targets (#50)

- tools/buildmgr/cbuildgen/installer/create_installer.sh
- tools/buildmgr/test/integrationtests/src/CPackGetTests.cpp
- Fix windows unzip command line for preventing local environment failings
- Move `PackAddAlreadyInstalledPackTest` into `PackAddPackInstallationTest` because it was not self-contained and it was failing depending on the test order.
- Update `PackAddValidFileArgTest` to download smaller packs
- Fix typos
> Fix CPackGetTests issues

- tools/buildmgr/cbuild/src/CbuildUtils.cpp
- tools/buildmgr/test/unittests/src/UtilsTests.cpp
This function is used when inserting toolchain flags into cmake variables `LD_FLAGS_GLOBAL` as well as `AS_FLAGS_*`, `CC_FLAGS_*` and `CXX_FLAGS_*` at all levels (global, groups, files).
> [buildmgr] Fix EscapeQuotes function to handle multiple escapes (#67)

- .github/workflows/packchk.yml
- .github/workflows/unit_test_results.yml
This patch aims to fix Publish Tests on PRs.
This only affects packchk. There is no support for other tools yet.
Fixed:
- Avoid running it after the PR is merged on `main`.
- Using the correct path to look for the test result files.
> Publish tests fix

- libs/rtemodel/include/RteInstance.h
- libs/rtemodel/include/RteProject.h
- libs/rtemodel/include/RteTarget.h
- libs/rtemodel/src/RteInstance.cpp
- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/src/RteTarget.cpp
- tools/buildmgr/cbuild/src/CbuildModel.cpp
Remove unnecessary rteFolder arguments (target knows its parent project)
Done to ensure backward compatibility with the code already using RteModel library
> Correct API introduced by #65

- .github/matrix_includes_buildmgr.json
- .github/matrix_includes_packchk.json
- .github/matrix_includes_packgen.json
- .github/matrix_includes_projmgr.json
- .github/matrix_includes_test_libs.json
- .github/matrix_includes_toolbox.json
- .github/workflows/buildmgr.yml
- .github/workflows/packchk.yml
- .github/workflows/packgen.yml
- .github/workflows/projmgr.yml
- .github/workflows/test_libs.yml
- .github/workflows/toolbox.yml
* Run macOS runners only on public repos
Creating an initial job `matrix_prep` to create a matrix set and its
includes.
In our case, it runs:
* mac, windows, linux on public repos
* windows and linux on private repos
The matrix data for each product can be found on:
* .github/matrix_includes_*.json
In the JSON file, there is an attribute called `runOn` for each
combination which has two values:
* always: always going to run regardless the repo type.
* publicRepo: only run on public repos.
> Run macOS runners only on public repos

- tools/projmgr/schemas/cdefault.schema.json
- tools/projmgr/schemas/clayer.schema.json
- tools/projmgr/schemas/cproject.schema.json
- tools/projmgr/schemas/csolution.schema.json
Previous JSON schema was valid (https://www.jsonschemavalidator.net/) but possibly not best.
Removes useless lines preventing https://quicktype.io/ to run.
`"additionalProperties": false` is part already of `./common.schema.json`
> [projmgr] Open door to vendor specific data addon: schema polishing

- .github/workflows/buildmgr.yml
- .github/workflows/packchk.yml
- .github/workflows/packgen.yml
- .github/workflows/projmgr.yml
- .github/workflows/test_libs.yml
- .github/workflows/toolbox.yml
Use the new Open-CMSIS-Pack/devtools-build-action location.
> GitHub Actions: update devtools-build-action location

- tools/buildmgr/cbuildgen/config/AC5.5.6.7.cmake
> [buildmgr] AC5 use cbuild_set_defines to set CC_DEFINES

- libs/rtemodel/include/RteCallback.h
- libs/rtemodel/src/RteCallback.cpp
- libs/rteutils/include/RteUtils.h
- libs/rteutils/src/RteUtils.cpp
- tools/buildmgr/cbuild/src/CbuildCallback.cpp
- tools/buildmgr/cbuild/src/CbuildKernel.cpp
- tools/projmgr/include/ProjMgrCallback.h
- tools/projmgr/src/ProjMgrCallback.cpp
- tools/projmgr/src/ProjMgrKernel.cpp
* Add $B processing to RteCallback::ExpandString()
Expands board name for the active target
* Add $B processing to RteCallback::ExpandString()
Expands board name for the active target
fix in RteUtils::ReplaceAll()
> Add $B processing to RteCallback::ExpandString() (#229)

- tools/projmgr/docs/Manual/Overview.md
Remove the duplicate section "Support for unnamed *.yml files" from the overview. The first copy of the section is maintained.
> [projmgr] Remove duplicate section from overview

- tools/packchk/src/ValidateSyntax.cpp
- tools/packchk/test/data/TestLicense/TestVendor.TestPackLicense.pdsc
- tools/packchk/test/data/TestLicense/licenses/license.dat
- tools/packchk/test/integtests/src/PackChkIntegTests.cpp
added: check license path for slashes
> packchk: Add a check for using forward slashes in <license> element Github#373 (#242)

- libs/rtemodel/src/RteKernel.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- libs/rtemodel/test/src/RteModelTestConfig.cpp
- libs/rtemodel/test/src/RteModelTestConfig.h
> [rtemodel] Retrieve local pack version from pdsc (#253)

- .github/matrix_includes_buildmgr.json
- .github/workflows/buildmgr.yml
- tools/buildmgr/cbuildgen/config/GCC.11.2.1.cmake
- tools/buildmgr/cbuildgen/installer/install.sh
- tools/buildmgr/test/integrationtests/src/DebPkgTests.cpp
- tools/buildmgr/test/integrationtests/src/InstallerTests.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestDefault/ref/build-types/project.Debug.cprj
- tools/projmgr/test/data/TestDefault/ref/build-types/project.Release.cprj
- tools/projmgr/test/data/TestDefault/ref/empty/project.Debug.cprj
- tools/projmgr/test/data/TestDefault/ref/empty/project.Release.cprj
- tools/projmgr/test/data/TestSolution/ref/GCC/test1.Release+TypeA.cprj
- tools/projmgr/test/data/TestSolution/ref/GCC/test1.Release+TypeB.cprj
- tools/projmgr/test/data/TestSolution/ref/test1.Release+CM0.cprj
- tools/projmgr/test/data/TestSolution/ref/test1.Release+CM0_board_package.cprj
Don't upgrade GCC in MacOS CI due to the following bug:
https://bugs.linaro.org/show_bug.cgi?id=5867
> [projmgr][buildmgr] Upgrade GCC support (#254)

- .github/matrix_includes_buildmgr.json
- .github/matrix_includes_packchk.json
- .github/matrix_includes_packgen.json
- .github/matrix_includes_projmgr.json
- .github/matrix_includes_test_libs.json
- .github/matrix_includes_toolbox.json
- .github/workflows/buildmgr.yml
- .github/workflows/packchk.yml
- .github/workflows/packgen.yml
- .github/workflows/projmgr.yml
- .github/workflows/test_libs.yml
- .github/workflows/toolbox.yml
- libs/crossplatform/src/LinuxDarwin_Process.cpp
The macOS-10.15 environment is deprecated and will be removed on August 30th, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583
> Update GH Actions macOS environment

- tools/projmgr/docs/Manual/YML-Format.md
The `[abc]` style wildcard is already supported as it is a common implementation.
Updating the documentation to be consistent with https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_conditions_pg.html#element_conditions
> Add [abc] style wildcard to pack name convention

- libs/rtemodel/src/RteCondition.cpp
follow referenced condition instead of returning false
> Bugfix to check if component is device dependent (#280)

- libs/rtefsutils/include/RteFsUtils.h
- libs/rtefsutils/src/RteFsUtils.cpp
- libs/rtefsutils/test/src/RteFsUtilsTest.cpp
- libs/rtemodel/src/RteKernel.cpp
- tools/buildmgr/cbuild/src/CbuildModel.cpp
- tools/packgen/src/PackGen.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
Split path normalizing and existence check as a preparation to make existence check optional. This shouldn't affect behavior.
Prerequisite for #432
Signed-off-by: Erik LUNDIN <erik.lundin@st.com>
> Don't require file to exist when normalizing path

- libs/rtemodel/test/src/RteModelTest.cpp
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- test/packs/ARM/RteTest_DFP/0.2.0/Components/BoardDependency.c
- test/packs/ARM/RteTest_DFP/0.2.0/Components/DeviceDependency.c
- test/projects/RteTestM3/RteTestM3_ConfigFolder.cprj
* Bugfix to check if component is device dependent
follow referenced condition instead of returning false
unit test
> Test case for device dependent components (#287)

- test/packs/ARM/RteTest/0.1.0/ARM.RteTest.pdsc
- test/packs/ARM/RteTest/0.1.0/Dummy/Subfolder/dummy.c
- test/packs/ARM/RteTest/0.1.0/Dummy/dummy.c
- tools/buildmgr/test/integrationtests/src/CBuildGCCTests.cpp
- tools/buildmgr/test/integrationtests/src/CBuildIntegTestEnv.cpp
- tools/buildmgr/test/testinput/Examples/GCC/DupFilename/CMakeLists.txt.ref
- tools/buildmgr/test/testinput/Examples/GCC/DupFilename/Project.cprj
- tools/buildmgr/test/testinput/Examples/GCC/DupFilename/main.c
Validate project compilation having component sources with same filenames
> [buildmgr] Add duplicated filenames test case (#285)

- tools/buildmgr/test/testinput/Examples/GCC/DupFilename/main.c
Call functions from the different sources so the symbols presence is checked during linking phase.
> [buildmgr] Update duplicated filename test case (#289)

- tools/buildmgr/cbuildgen/config/CPRJ.xsd
- tools/projmgr/src/ProjMgrGenerator.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestProject/test_only_board.cprj
- tools/projmgr/test/data/TestSolution/ref/test1.Debug+CM0_board_package.cprj
- tools/projmgr/test/data/TestSolution/ref/test1.Release+CM0_board_package.cprj
* [projmgr] Support Bversion alongside Brevision for backward compatibility
* [buildmgr] Update CPRJ.xsd version
> [projmgr] Support Bversion alongside Brevision for backward compatibility (#290)

- CMakeLists.txt
Add MSVC option for consistently using UTF-8 instead of environment specific code pages
> Add MSVC option for consistently using UTF-8

- libs/rtemodel/include/RteTarget.h
- libs/rtemodel/src/RteCallback.cpp
- test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc
- test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.bat
- test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.sh
- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestSolution/TestProject3/TestProject3.cproject.yml
- tools/projmgr/test/data/TestSolution/TestProject3/main.c
- tools/projmgr/test/data/TestSolution/gendir.csolution.yml
- tools/projmgr/test/data/TestSolution/outdirs.csolution.yml
- tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Add support for `$G` variable on `<generator>` element in .pdsc format as implemented in https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/pull/151
Add support for `gendir` on the `output-dirs` property to allow customizing the `destination` property in the generator input file as described in https://github.com/Open-CMSIS-Pack/devtools/issues/433
Contributed by STMicroelectronics.
> Add support for output-dirs[gendir] and $G

- .github/workflows/buildmgr.yml
png, pptx and svg are other documentation related file extension which should not trigger any build, test, coverage nor lint actions.
> exclude more file types

- tools/projmgr/docs/Manual/Overview.md
- tools/projmgr/docs/Manual/YML-Input-Format.md
Simplified `component instances:` (https://github.com/Open-CMSIS-Pack/devtools/issues/489)
Added --load option to specify the behavior with loading packs.
> csolution documentation: Component Instances, --load option for packs

- tools/svdconv/SVDConv/src/SVDConv.cpp
- tools/svdconv/SVDConv/src/SVDConv_Msgs.cpp
- tools/svdconv/SVDConv/src/SvdOptions.cpp
- print programm header when -b log.txt is used
- fixed "File/Path not found"
Co-authored-by: Thorsten de Buhr <thorsten.deBuhr@arm.com>
> packchk: Fixed minor issues overlooked during initial contribution

- tools/projmgr/docs/Manual/Overview.md
Use .base suffix for versioned files:
- .current is ambiguous
- consistent with Git, where base and update terms are used.
> PLM of config files: use .base instead of .current

- libs/xmlreader/include/XML_Reader.h
- libs/xmlreader/src/XML_Reader_Msgs.cpp
- libs/xmltreeslim/src/XmlTreeSlimInterface.cpp
- tools/packchk/include/ValidateSemantic.h
- tools/packchk/src/PackChk_Msgs.cpp
- tools/packchk/src/ValidateSemantic.cpp
- tools/packchk/test/data/CompResolvedByItself/ARM.CompResolvedByItself.pdsc
- tools/packchk/test/integtests/src/PackChkIntegTests.cpp
* Prepare for new check
* Preparation
* PackChk:
added:
- GitHub #510: Add validation rule that detects a dependency rule satisfied by the component itself
Message:
*** WARNING M389: ARM.GitHub#510.pdsc (Line 17) The component 'ARM::C.G(cond1)[]' (Line 17) has dependency 'SW' : 'require C:G' that is resolved by the component itself.
* added test case
* fixed issues
* Fixed: Test expected return value
> Add validation rule that detects a dependency satisfied by the component itself (#339)

- tools/svdconv/SVDConv/src/SVDConv_Msgs.cpp
An error from previous SVDConv releases has been fixed here, which would throw an error in PackInstaller for STM32F40x.svd (with address blocks exceed 32 Bit)
> SVDConv: M380 from ERROR into WARNING due to a fix to address block verification.

- tools/projmgr/docs/Manual/YML-Input-Format.md
- `processor:` added name  (pname) specification at cproject.yml level
- `setups:` extended with processor attributes
> Additions to YML-Input-Format.md

- tools/svdconv/SVDConv/src/SvdOptions.cpp
print SVDConv header when log file "-b log.txt" is written (instead of being completely silent)
> fixed: (#367)

- libs/rtemodel/src/RteProject.cpp
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/src/ProjMgrGenerator.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/TestSolution/pre-include.cproject.yml
- tools/projmgr/test/data/TestSolution/pre-include.csolution.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Release+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cprj
- tools/projmgr/test/data/TestSolution/ref/pre-include.cbuild-idx.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
* [projmgr] Extend cbuild.yml output nodes
- pre-includes
- constructed files
- file categories and attributes
- output dirs
- config files versions
- component generator IDs
> [projmgr] Extend cbuild.yml output nodes (#370)

- tools/buildmgr/docs/cbuild.md
- tools/cpackget/docs/cpackget.md
- tools/projmgr/docs/Manual/Overview.md
- tools/projmgr/docs/Manual/YML-Input-Format.md
Added `device:` to cproject.yml as it allows to specify the processor core (pname).
Removed `processor:` name (as this is implemented via `device:` 
Added proposal `output:` to provide more flexiblity for output control 
Reflected CMSIS-Toolbox 1.3 command line parameters
> CMSIS-Toolbox 1.3 Documentation Updates

- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestLayers/ref/variables/variables.BuildType1+TargetType1.cprj
- tools/projmgr/test/data/TestLayers/ref/variables/variables.BuildType1+TargetType2.cprj
- tools/projmgr/test/data/TestLayers/ref/variables/variables.BuildType2+TargetType1.cprj
- tools/projmgr/test/data/TestLayers/ref/variables/variables.BuildType2+TargetType2.cprj
- tools/projmgr/test/data/TestLayers/variables-redefinition.cproject.yml
- tools/projmgr/test/data/TestLayers/variables-redefinition.csolution.yml
- tools/projmgr/test/data/TestLayers/variables.cproject.yml
- tools/projmgr/test/data/TestLayers/variables.csolution.yml
- tools/projmgr/test/data/TestLayers/variables/app.clayer.yml
- tools/projmgr/test/data/TestLayers/variables/build1.clayer.yml
- tools/projmgr/test/data/TestLayers/variables/build2.clayer.yml
- tools/projmgr/test/data/TestLayers/variables/target1.clayer.yml
- tools/projmgr/test/data/TestLayers/variables/target2.clayer.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address [#proposals-for-layers](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/YML-Input-Format.md#proposals-for-layers)
Accept `variables` node at csolution, build-types and target-types levels
Expand `variables` in references to clayers
Internals: shift clayer parsing to allow timely variables parsing; uniform variables and static access sequences expansion
Add test cases
> [projmgr] Add `variables` handling

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address segmentation fault reported in https://github.com/Open-CMSIS-Pack/devtools/issues/657
> [projmgr] Check component file pointer

- libs/rtemodel/include/RteAttributes.h
- libs/rtemodel/include/RteExample.h
- libs/rtemodel/include/RteInstance.h
- libs/rtemodel/include/RteItem.h
- libs/rtemodel/src/RteAttributes.cpp
- libs/rtemodel/src/RteDevice.cpp
- libs/rtemodel/src/RteExample.cpp
- libs/rtemodel/src/RteInstance.cpp
- libs/rtemodel/src/RteItem.cpp
- libs/rtemodel/test/CMakeLists.txt
- libs/rtemodel/test/src/RteChk.cpp
- libs/rtemodel/test/src/RteChk.h
- libs/rtemodel/test/src/RteChkMain.cpp
- libs/rtemodel/test/src/RteChkTest.cpp
- libs/xmltree/include/XmlItem.h
- libs/xmltree/src/XmlItem.cpp
- libs/xmltree/test/src/XmlTreeTest.cpp
- tools/buildmgr/cbuild/src/CbuildLayer.cpp
* RTE Model refactoring: preparation
Several methods moved from RteAttributes to RteItem
Member variables of RteAttributes type replaced by RteItem
RteAttributes is derived from XmlItem, redundant methods removed
RteChk executable is added to improve testing
> RTE Model refactoring: preparation (#424)

- tools/packchk/src/PackChk_Msgs.cpp
- tools/packchk/src/ValidateSyntax.cpp
- tools/packchk/test/data/SemVerTest/Arm.SemVerTest_DFP.pdsc
- M396 to ERROR
- no check for ascending date anymore
- added case to test data
> [packchk] Rework Message M396

- tools/packchk/include/CheckFiles.h
- tools/packchk/src/CheckFiles.cpp
- tools/packchk/src/PackChk_Msgs.cpp
- tools/packchk/test/unittests/src/TestCheckFiles.cpp
added Implementation + Test. case.
"M314", LEVEL_WARNING, "Filename '%NAME%' contains whitespaces, this is not recommended"
> PackChk should check for spaces in the name element of the <file> tag (#451)

- libs/rtemodel/include/RteGenerator.h
- libs/rtemodel/include/RteItem.h
- libs/rtemodel/src/RteGenerator.cpp
- libs/rtemodel/src/RteItem.cpp
- libs/rteutils/include/RteUtils.h
- libs/rteutils/src/RteUtils.cpp
- test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/cbuild.schema.json
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.cbuild-idx.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Release+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml
- tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Implements required things in the cbuild.yml according to [Generator (Proposal).md](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Generator%20(Proposal).md) and https://github.com/Open-CMSIS-Pack/devtools/issues/434#issuecomment-1337608400
Adds the following information when generating `*.cbuild.yml` files:
- csolution
- cproject
- input to component generators:
* generator command
* arguments
* files
* gpdsc file
* working directory
In addition, this switches to use `*.cbuild.yml` as input to generators (`$G` set correspondingly)
Limitations/future work:
- In addition to device, board should probably be added to the build description schema and implementation
- GPDSC is not used to update `*.cbuild.yml`
- Working dir is inconsistent between …
> cbuild.yml as generator input

- libs/crossplatform/CMakeLists.txt
- libs/crossplatform/test/CMakeLists.txt
- libs/rtefsutils/CMakeLists.txt
- libs/rtemodel/include/RteComponent.h
- libs/rtemodel/include/RteInstance.h
- libs/rtemodel/include/RteItem.h
- libs/rtemodel/include/RteModel.h
- libs/xmltree/include/XmlItem.h
- libs/xmltree/include/XmlTreeItem.h
Fixes miscellaneous warnings when building with Clang 15.
Signed-off-by: Erik MÅLLBERG <erik.lundin@st.com>
> Clang 15 warnings

- libs/crossplatform/CMakeLists.txt
- libs/crossplatform/test/CMakeLists.txt
- libs/rtefsutils/CMakeLists.txt
- tools/projmgr/src/ProjMgrGenerator.cpp
This fixes building for GCC 8. I found out that people still [build with Ubuntu 18](https://github.com/Open-CMSIS-Pack/devtools/issues/696) and [some changes](https://github.com/Open-CMSIS-Pack/devtools/pull/737/commits/e7b1121d2218247ea8fd2025cf24a51bfdb61669) in #737 didn't account for that.
- Restore explicit linking with `stdc++fs` (but only for GCC 8)
- Add missing header (didn't build on GCC 8.4.0 without this)
Signed-off-by: Erik MÅLLBERG <erik.lundin@st.com>
@edriouk Please review :)
> Fixes for GCC 8

- tools/packchk/include/ValidateSemantic.h
- tools/packchk/src/ValidateSemantic.cpp
added:
- iteration over possible TrustZone variants, if available
- skipping Test for system_ and startup_ if generator is involved
https://github.com/Arm-Debug/devtools-external/pull/479
> PackChk reports INFO messages when generate STM32L5xx_DFP and STM32L0xx_DFP (#479)

- tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake
Projects may fail with compiler error:
```Unexpected command line arguments: -include```
The correct compiler flag is `--preinclude`
> [buildmgr] Fix projects using preincludes in IAR

- .github/workflows/buildmgr.yml
- .github/workflows/nightly.yml
- .github/workflows/packchk.yml
- .github/workflows/packgen.yml
- .github/workflows/projmgr.yml
- .github/workflows/svdconv.yml
- .github/workflows/test_libs.yml
The gcc-arm installer archive is huge. To prevent downloading the file for each run it is cached in GitHub based on the download url cache-key.
> GitHub: Cache gcc-arm installer

- libs/rtemodel/src/RteProject.cpp
in case the file version matches the component version
fixed by explicitly asking for the file instance version
> prjmgr] Base files for config files are created unconditionally (#496)

- libs/rtemodel/include/RteComponent.h
- libs/rtemodel/include/RteDevice.h
- libs/rtemodel/include/RteInstance.h
- libs/rtemodel/include/RteItem.h
- libs/rtemodel/include/RteKernel.h
- libs/rtemodel/include/RtePackage.h
- libs/rtemodel/src/RteComponent.cpp
- libs/rtemodel/src/RteDevice.cpp
- libs/rtemodel/src/RteItem.cpp
- libs/rtemodel/src/RteModel.cpp
- libs/rtemodel/src/RtePackage.cpp
- libs/rtemodel/test/src/RteChk.cpp
- libs/xmltree/include/XMLTree.h
- libs/xmltree/include/XmlTreeItem.h
- libs/xmltree/include/XmlTreeItemBuilder.h
- tools/packchk/src/CheckComponents.cpp
- tools/packchk/src/CheckConditions.cpp
- tools/packchk/src/CheckFiles.cpp
- tools/packchk/src/GatherCompilers.cpp
- tools/packchk/src/RteModelReader.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/svdconv/SVDModel/src/SvdDevice.cpp
- tools/svdconv/SVDModel/src/SvdItem.cpp
- tools/svdconv/SVDModel/src/SvdModel.cpp
* RTE Model refactoring:
derive RteItem from XmlTreeItem<RteItem>
make VISIT result class enum
remove duplicated methods from RteItem
use size_t instead of int for collection sizes
add RteComponentInstance::GetComponent() override to simplify logic
simplify XmlTreeItem::AddChild()
> RTE Model refactoring: (#494)

- libs/crossplatform/CMakeLists.txt
- libs/crossplatform/src/Darwin/constants.h
somehow things are screwed up on macOS. I am expecting to use $HOME/.cache/arm/packs if XDG_CACHE_HOME is not set.
> Use XDG_CACHE_HOME for macOS

- tools/svdconv/SVDGenerator/include/HeaderData.h
- tools/svdconv/SVDGenerator/src/HeaderData_Field.cpp
- tools/svdconv/SVDGenerator/src/HeaderData_Register.cpp
Bitfields are now generated in separate structs inside register union, if overlapping
> SVDConv: fix bitfield generator for unions (#499)

- libs/rtemodel/src/RteTarget.cpp
- test/packs/ARM/RteTestBoard/0.1.0/ARM.RteTestBoard.pdsc
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h
- test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h
* [csolution] Generate regions_*.h file from memory tags #739 (#500) (#789)
bugfix: use __RAM for rw memory
extend noInit testing
* Bugfix in calculating pack ID in RtePackageInstanceInfo (merge)
> Ram (#510)

- tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake
Addresses Open-CMSIS-Pack/devtools#858
Reverts partially Open-CMSIS-Pack/devtools#798
Reapplies fix from Open-CMSIS-Pack/devtools#737
> Fix IAR Compiler preinclude flag (#536)

- tools/buildmgr/cbuild/src/CbuildProject.cpp
- tools/projmgr/src/ProjMgrUtils.cpp
* [cbuildgen] regression with 1.6.0: gpdsc file ignored #860
Fixed by setting PackageState::PS_GENERATED on RtePackage creation
* [cbuildgen] regression with 1.6.0: gpdsc file ignored #860
Fixed by setting PackageState::PS_GENERATED on RtePackage creation
* Update tools/buildmgr/cbuild/src/CbuildProject.cpp
* Update tools/buildmgr/cbuild/src/CbuildProject.cpp
---------
> [cbuildgen] regression with 1.6.0: gpdsc file ignored #860 (#539)

- libs/rtemodel/src/RteCprjProject.cpp
- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/src/RteTarget.cpp
- libs/rteutils/include/VersionCmp.h
- libs/rteutils/src/VersionCmp.cpp
- libs/rteutils/test/src/VersionCmpTests.cpp
- test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.bat
- test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.sh
- test/packs/ARM/RteTestGenerator/0.1.0/Templates/RteTest.gpdsc.template
- test/packs/ARM/RteTestGenerator/0.1.0/Templates/RteTest_Generated_Component.c.template
- test/projects/RteTestM4/RteTestM4_Board.cprj
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestGenerator/RTE/Device/RteTestGen_ARMCM0/RteTest.gpdsc
- tools/projmgr/test/data/TestGenerator/RTE/Device/RteTestGen_ARMCM0/RteTest_Generated_Component.c
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
* [cbuildgen] regression with 1.6.0: gpdsc file ignored #860
set PackageState::PS_GENERATED on RtePackage creation
correction to fix "enforced component" misbehavior
tests added
> Issue860 1 (#542)

- libs/rteutils/include/VersionCmp.h
> Restore VersionCmp::MatchMode::ANY_VERSION since it is used in pack Installer (#553)

- tools/projmgr/src/ProjMgrYamlEmitter.cpp
When `CMSIS_COMPILER_ROOT` isn't given, `ProjMgrYamlCbuild::FormatPath()` incorrectly inserted `"${CMSIS_COMPILER_ROOT}"` in front of all paths in the `*.cbuild.yml` file (unless located below `${CMSIS_PACK_ROOT}` instead of creating relative paths.
Signed-off-by: Erik MÅLLBERG <erik.mallberg@st.com>
> Ignore empty CMSIS_COMPILER_ROOT

- libs/rtefsutils/include/RteFsUtils.h
- libs/rtefsutils/src/RteFsUtils.cpp
- libs/rtefsutils/test/src/RteFsUtilsTest.cpp
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Release+CM0.cprj
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Release+CM3.cprj
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences2.Release+CM0.cprj
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences2.Release+CM3.cprj
- tools/projmgr/test/data/TestAccessSequences/test-access-sequences.csolution.yml
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/841#issuecomment-1538663259
For access sequences resulting in relative paths inside `misc` options, add the heading dot `./` to evidence it is a relative path and not other miscellaneous values so the build manager can process it correctly.
> [projmgr] Format relative paths in `misc` options

- tools/packchk/src/PackChk.cpp
- tools/packchk/src/PackChk_Msgs.cpp
- tools/packchk/src/PackOptions.cpp
Also checked M313 against mapped drive on windows, e.g. "subst D: C:\D" (for path "C:\D")
> PackChk: improved error reporting for invalid command line and when PACK.XSD has not been found. (#559)

- libs/rtefsutils/src/RteFsUtils.cpp
- libs/rtefsutils/test/src/RteFsUtilsTest.cpp
- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences3.Release.cprj
- tools/projmgr/test/data/TestAccessSequences/test-access-sequences1.cproject.yml
- tools/projmgr/test/data/TestAccessSequences/test-access-sequences2.cproject.yml
- tools/projmgr/test/data/TestAccessSequences/test-access-sequences2.csolution.yml
- tools/projmgr/test/data/TestAccessSequences/test-access-sequences3.cproject.yml
- tools/projmgr/test/data/TestSolution/outdirs.csolution.yml
Relates to https://github.com/Open-CMSIS-Pack/devtools/issues/894
Exceptions:
- The access sequences `elf`, `bin`, `hex`, `lib`, `cmse-lib` must be refined after https://github.com/Open-CMSIS-Pack/devtools/issues/895
> [projmgr] Update access sequences

- tools/packchk/include/PackOptions.h
- tools/packchk/include/ParseOptions.h
- tools/packchk/src/PackChk.cpp
- tools/packchk/src/PackOptions.cpp
- tools/packchk/src/ParseOptions.cpp
added:
- option "--pedantic" (as bool), where packchk returns 1 on WARNINGs
- prepared for "--pedantic [warning|info]", this would touch ErrLog library
> Add option to packchk to fail if warning/info violations are detected #886 (#583)

- libs/rtemodel/include/RteItem.h
- libs/rtemodel/include/RtePackage.h
- libs/rtemodel/src/RteItem.cpp
- libs/rtemodel/src/RtePackage.cpp
- libs/rtemodel/src/RteTarget.cpp
* Add initial support for <licenseSet> elements to RTE model
> Add initial support for <licenseSet> elements to RTE model (#593)

- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- tools/packchk/src/CheckConditions.cpp
- tools/packchk/src/PackChk_Msgs.cpp
- tools/packchk/test/integtests/src/PackChkIntegTests.cpp
* [packchk] missing component (Cvariant) not detected when specified in <accept> (M504:) #1052
added missing checks
added test cases
> [packchk] missing component (Cvariant) not detected when specified in <accept> (M504:) #1052 (#650)

- tools/projmgr/src/ProjMgrKernel.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Scenario:
csolution.yml:
```yml
packs:
- pack: ARM::CMSIS@5.9.0
path: ./ARM.CMSIS.5.9.0/
```
cproject.yml:
```yml
packs:
- pack: ARM.CMSIS@5.9.0
```
In the above scenario, the same pack is defined on 2 different paths. The one in the csolution.yml is a project local path, and for the cproject.yml, it can be found in the $CMSIS_PACK_ROOT.
As the RteModel does not allow "duplicates", the RtePackage pointer, for the second pdsc file to be loaded, will be released when calling RteModel->Validate() and thus, only instances that is known by the model should be contained in m_loadedPacks in the ProjMgrWorker instance.
> Fix crash when same pack is located on 2 paths

- tools/packchk/include/PackOptions.h
- tools/svdconv/SVDConv/include/SvdOptions.h
- tools/svdconv/SVDModel/include/SvdTypes.h
- tools/svdconv/SVDModel/include/SvdUtils.h
Using integer types with specific width requirements requires such as `uint32_t` requires including `<cstdint>`.
> Add missing includes

- libs/rtemodel/include/RteGenerator.h
- libs/rtemodel/src/RteGenerator.cpp
- libs/rtemodel/test/src/RteChkTest.cpp
- test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc
- test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.bat
- test/packs/ARM/RteTestGenerator/0.1.0/Generator/script.sh
- tools/projmgr/include/ProjMgr.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestSolution/TestProject3_3/TestProject3_3.cproject.yml
- tools/projmgr/test/data/TestSolution/gen_nodryrun.csolution.yml
- tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Running generators in dry-run mode, expect the GPDSC content to be output to stdout. This allows consuming tools to parse the GPDSC and for example resolve dependencies without any files being updated on disk.
The csolution tool doesn't currently use the dry-run output from the generator. Since log messages from csolution and the generator also are written to stdout, the generator need to enclose the GPDSC content within special begin and end marks, so a tool running `csolution --dry-run run` has to ignore everything outside those marks.
Begin and end marks are currently not fixed, but would preferably be chosen to be consistent to avoid surprises.
Suggested begin mark: -----BEGIN GPDSC-----
Suggested end mark:   -----END GPDSC-----
Contributes to …
> Support dry-running generators

- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestSolution/Portability/portability.csolution.yml
- tools/projmgr/test/data/TestSolution/Portability/portability2.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- Check `pack` `path` portability
- Avoid warning paths with access sequences
> [projmgr] Update portability check

- libs/rtemodel/include/RteInstance.h
- libs/rtemodel/src/RteInstance.cpp
- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- libs/rteutils/include/RteConstants.h
- tools/projmgr/include/ProjMgr.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
* [csolution] Add list configs command to list configuration files #922
> [csolution] Add list configs command to list configuration files #922 (#661)

- tools/svdconv/SVDGenerator/src/PartitionData.cpp
- tools/svdconv/SVDModel/src/SvdCpu.cpp
- tools/svdconv/Test/data/sauConfig/SSE300_errs.svd
- tools/svdconv/Test/data/sauConfig/SSE300_ok.svd
- tools/svdconv/Test/integtests/src/SvdConvIntegTests.cpp
fixed:
- check for initialized value of sau num regions
> [SVDConv] runs in infinite loop when using generate partition on SVD file without <sauNumRegions> element under <cpu> #1082 (#671)

- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestLayers/genericlayers.cproject.yml
- tools/projmgr/test/data/TestLayers/genericlayers.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Introduce `optional` flag when requiring layers by its `type`, default `true`.
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1092.
> [projmgr] Update `list layers` behaviour: consider layer type optional by default

- libs/rtemodel/test/src/RteModelTest.cpp
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- test/packs/ARM/RteTest_DFP/0.2.0/Layers/board-specific.clayer.yml
- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrUtils.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestLayers/genericlayers.cproject.yml
- tools/projmgr/test/data/TestLayers/genericlayers.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Rework layer discovering initial steps for clear processing and filtering of candidate layers.
Address second issue from https://github.com/Open-CMSIS-Pack/devtools/issues/1092.
> [projmgr] Update `list layers` behaviour: load device/board specific packs

- tools/buildmgr/cbuildgen/CMakeLists.txt
- tools/buildmgr/cbuildgen/src/cbuildgen.manifest
- tools/packchk/CMakeLists.txt
- tools/packchk/src/packchk.manifest
- tools/packgen/CMakeLists.txt
- tools/packgen/src/packgen.manifest
- tools/projmgr/CMakeLists.txt
- tools/projmgr/src/csolution.manifest
- tools/svdconv/SVDConv/CMakeLists.txt
- tools/svdconv/SVDConv/src/svdconv.manifest
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
Address https://github.com/Open-CMSIS-Pack/devtools/issues/838
> [devtools] Add Windows manifest enabling `longPathAware`

- libs/rtemodel/include/RteCallback.h
- libs/rtemodel/src/RteComponent.cpp
- libs/rtemodel/test/src/RteChkTest.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Revised Generator Workflow Proposal #1112
support in RteModel
* Update libs/rtemodel/test/src/RteModelTest.cpp
---------
> Revised Generator Workflow Proposal #1112 (#689)

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestSolution/typefilters.cproject.yml
- tools/projmgr/test/data/TestSolution/typefilters.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/926
> [projmgr] Add `for-context` and `for-compiler` spelling check

- tools/projmgr/templates/cdefault.yml
- Arm Compiler does this by default
- GCC/Clang require according flags
- IAR does this by default
Fixes #1128
> Projmgr: cdefault flags to remove unused sections

- CMakeLists.txt
- libs/rteutils/include/RteUtils.h
- libs/rteutils/src/RteUtils.cpp
- libs/xmltree/include/AbstractFormatter.h
- libs/xmltree/include/IXmlItemBuilder.h
- libs/xmltree/include/JsonFormatter.h
- libs/xmltree/include/XMLTree.h
- libs/xmltree/include/XmlFormatter.h
- libs/xmltree/include/XmlTreeItemBuilder.h
- libs/xmltree/src/AbstractFormatter.cpp
- libs/xmltree/src/JsonFormatter.cpp
- libs/xmltree/src/XMLTree.cpp
- libs/xmltree/src/XmlFormatter.cpp
- libs/xmltreeslim/src/XmlTreeSlimInterface.cpp
- libs/ymltree/CMakeLists.txt
- libs/ymltree/include/YmlFormatter.h
- libs/ymltree/include/YmlTree.h
- libs/ymltree/src/YmlFormatter.cpp
- libs/ymltree/src/YmlTree.cpp
- libs/ymltree/src/YmlTreeParserInterface.cpp
- libs/ymltree/src/YmlTreeParserInterface.h
- libs/ymltree/test/CMakeLists.txt
- libs/ymltree/test/YmlTreeTest.cpp
- libs/ymltree/test/YmlTreeTest.cpp_.cpp
* YmlTree parser
Generic XmlTreeItem tree for YAML files 
---------
> YmlTree parser (#686)

- libs/rtemodel/include/RteDevice.h
- libs/rtemodel/src/RteDevice.cpp
> Bugfix: repair collecting effective debug sequences (#694)

- tools/projmgr/test/data/TestDefault/ref/empty/project.Debug+TEST_TARGET.cbuild.yml
- tools/projmgr/test/data/TestDefault/ref/empty/project.Release+TEST_TARGET.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/multiple-components.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-layer.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-multiple-generators.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project1.Debug+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project1.Release+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project2.Debug+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project2.Release+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/LanguageAndScope/ref/lang-scope.Debug_AC6+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_AC6+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.Debug_GCC+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.PriorityDefines+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.PriorityRegions+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/StandardLibrary/ref/library.Debug+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test1.Release+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/cbuild/test2.Debug+CM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/outputFiles.Debug+Target.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/outputFiles.Library+Target.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/pre-include+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/rtedir.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/rtedir.Release+CM0.cbuild.yml
- tools/projmgr/test/src/ProjMgrTestEnv.cpp
Previously, files with different number of lines could be considered equal, since the comparison stopped with success when any of the files ended.
> Make files with different number of lines unequal

- libs/rtemodel/src/RtePackage.cpp
- libs/xmltree/include/XmlItem.h
- libs/xmltree/src/XmlItem.cpp
- libs/xmltree/test/src/XmlTreeTest.cpp
* Erase all xmlns: and xs: attributes when reading packs
no need in that info (we do not write packs back)
> Erase all xmlns: and xs: attributes when reading packs (#695)

- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/TestGenerator/ref/multiple-components.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-layer.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-multiple-generators.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/TestProject3_4/TestProject3_4.cproject.yml
- tools/projmgr/test/data/TestSolution/TestProject3_4/main.c
- tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild-gen.yml
- tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild.yml
- tools/projmgr/test/data/TestSolution/test_fail_creating_directories.csolution.yml
- tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.h
To facilitate implementation of generators, create `*.cbuild-gen.yml` with:
- any file and directory paths inside expanded to `absolute paths` in cbuild-gen.yml.
- new node, `current-generator` that can be used to identify what generator node in the cbuild-gen.yml that the current invocation is for.
Both `*.cbuild.yml` and `*.cbuild-gen.yml` are created inside the `intdir`, since they are both temporary files used by generators and builders.
The `$G` parameter for generators now expands to the `*.cbuild-gen.yml` file.
In both *.cbuild.yml and *.cbuild-gen.yml, all generator nodes now also includes the `from-pack` node that defines in what pack that the generator was defined.
For more background, see [2023-08-22 Open-CMSIS-Pack meeting](https://linaro.atlassian.net/wiki/spaces/CMSIS/pages/2 …
> Implement *.cbuild-gen.yml

- libs/rtemodel/include/RteModel.h
- libs/rtemodel/src/RteModel.cpp
- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/test/src/RteConditionTest.cpp
- libs/xmltree/src/XmlItem.cpp
* List available API versions
* Update XmlItem.cpp
---------
> List available API versions (#696)

- tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake
#1146 
Since hardware is double or nothing:
- Selecting SP_FPU should map onto DP hardware on Cortex-M55 and M85. 
- Did not change the behavior for A-series processors. Here ARMCLANG maps SP_FPU -> NO_FPU which hardly seems correct, so throwing error here does not seem too bad.
- R52 and R52+ Does not support SP_FPU yet, it's a known issue EWARM-9425
> IAR single precision FPU error

- tools/projmgr/include/ProjMgrExtGenerator.h
- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrExtGenerator.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/templates/global.generator.yml
- tools/projmgr/test/data/ExternalGenerator/global.generator.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addresses https://github.com/Open-CMSIS-Pack/devtools/issues/1171
> [projmgr] Extend list generators in verbose mode

- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1199
> [projmgr] Option -S without -c should issue a warning when cbuild-set.yml is not present

- tools/projmgr/templates/ac6_linker_script.sct.src
- added .bss at beginning of the .noinit section names as required by Arm Compiler 6
> [projmgr] Update default linker script for AC6

- libs/rtemodel/src/RteKernel.cpp
- tools/buildmgr/test/integrationtests/src/CBuildGenTestFixture.cpp
- tools/buildmgr/test/integrationtests/src/CBuildGenTests.cpp
- tools/buildmgr/test/testinput/ModelTest/InvalidPackRepo.cpinstall.json.ref
- tools/buildmgr/test/testinput/ModelTest/InvalidPackRepo.cpinstall.ref
- tools/buildmgr/test/testinput/ModelTest/InvalidPackRepo.cprj
Fixes https://github.com/Open-CMSIS-Pack/devtools/issues/1232
Added `CBuildGenTests.GeneratePackListTest_InvalidRepository` test case.
> [rtemodel] Restore `RteKernel::GetUrlFromIndex` return value when local pack repo is absent

- libs/rtemodel/include/RteKernel.h
- libs/rtemodel/src/RteComponent.cpp
- libs/rtemodel/src/RteKernel.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
bugfix in getting component bundle
added RteModel parameter to RteKernel::LoadPacks()
removed unused NULL_RTE_KERNEL
> RTE Model fixes and enhancements

- tools/projmgr/include/ProjMgr.h
- tools/projmgr/src/ProjMgr.cpp
separate code from ProjMgr::RunProjMgr() into ParseCommandLine() and ProcessCommands() methods
> Split RunProjMgr code (#750)

- libs/rtemodel/include/RteProject.h
- libs/rtemodel/src/RteCprjProject.cpp
- libs/rtemodel/src/RteKernel.cpp
- libs/rtemodel/src/RteProject.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
* Dedicated method to Update RTE folder
> Dedicated method to Update RTE folder

- libs/rtemodel/src/RteProject.cpp
- tools/buildmgr/test/testinput/Examples/GCC/TrustZone/CM33_s/RTE/Device/ARMCM33_DSP_FP_TZ/gcc_arm.ld.base@1.0.0
- tools/projmgr/include/ProjMgr.h
- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrParser.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestSolution/PackLocking/cbuild_pack_frozen.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/cbuild_pack_frozen.csolution.yml
- tools/projmgr/test/data/TestSolution/PackLocking/cbuild_pack_frozen_no_pack_file.csolution.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/cbuild_pack_frozen.cbuild-pack.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
The `--frozen-packs` option is only applicable for the following commands:
- `convert`
- `update-rte`
If `cbuild-pack.yml` needs to be created or updated, then `--frozen-pack` will treat this as an error and fail the command.
> [projmgr] Add --frozen-packs argument to csolution

- libs/rtemodel/include/RteKernel.h
- libs/rtemodel/include/RtePackage.h
- libs/rtemodel/src/RteKernel.cpp
- libs/rtemodel/src/RtePackage.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
* RtePackRegistry: add methods to erase and replace packs
> RtePackRegistry: add methods to erase and replace packs

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestSolution/PackLocking/project_pack_lock_find_unspecified_pack_using_load_argument.csolution.yml
- tools/projmgr/test/data/TestSolution/PackLocking/project_pack_lock_using_load_argument.csolution.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_find_unspecified_pack_using_load_argument-all.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_find_unspecified_pack_using_load_argument-latest.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_find_unspecified_pack_using_load_argument-required.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_find_unspecified_pack_using_load_argument-required_updated.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_using_load_argument-all.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_using_load_argument-latest.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/PackLocking/ref/project_pack_lock_using_load_argument-required.cbuild-pack.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
When `--load all` or `--load latest` argument is provided, the content of `cbuild-pack.yml` files should not be considered, but the file should be updated with the new resolved packs.
> [projmgr] Don't consider cbuild-pack.yml with --load <all|latest> (#1291)

- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/src/ProjMgrParser.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
Support for external generators in RTE Model
remove obsolete unused code
> Support for external generators in RTE Model (continue)

- libs/rtemodel/src/RteModel.cpp
- libs/rtemodel/src/RtePackage.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
fixed API handling, tests introduced
> RTE: Pack description tag dominate does not overrule API

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestSolution/pack_missing.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
This change request addresses updating the context-specific missing pack information within the individual context data structure, as well as printing the relevant missing packs information for each context.
for the same example for conversion:
Earlier
```
error csolution: required pack: ARM::Missing_DFP@0.0.9 not installed
error csolution: processing context 'test1+CM0' failed
error csolution: required pack: ARM::Missing_DFP@0.0.9 not installed
error csolution: processing context 'test1+Gen' failed
```
After this change
```
error csolution : required pack : ARM::Missing_DFP@0.0.9 not installed
error csolution : processing context 'test1+CM0' failed
error csolution : required pack : ARM::Missing_PACK@0.0.1 not installed
error csolution : processing context 'test1+Gen' failed
```
> Update/Get context specific pack missing info (#809)

- libs/rtemodel/src/RteKernel.cpp
- libs/xmltree/include/IXmlItemBuilder.h
This reverts a change introduced by PR
Support for external generators in RTE Model (#1335)
> Remove redundant inheritance in IXmlItemBuilder

- libs/rtemodel/include/RteProject.h
- libs/rtemodel/src/RteCprjProject.cpp
- libs/rtemodel/src/RteProject.cpp
- tools/buildmgr/cbuild/src/CbuildModel.cpp
rename one of RteProject::GetFileInstances() methods
to RteProject::GetFileInstancesForComponent() to avoid confusion
> Rename one of RteProject::GetFileInstances()

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/TestGenerator/GpdscWithProjectFiles/RteTestGeneratorIdentifier/RteTestGen_ARMCM0/RteTest.gpdsc
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-project-files.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestGenerator/test-gpdsc-project-files.cproject.yml
- tools/projmgr/test/data/TestGenerator/test-gpdsc-project-files.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Co-authored-by: Evgueni Driouk <edriouk@arm.com>
> [projmgr] Add gpdsc `project_files` into *.cbuild.yml group files

- tools/projmgr/templates/iar_linker_script.icf.src
ROM1 and RAM1 have incorrect BASE (used ROM0 and RAM0 instead. Corrected to use ROM1 and RAM1 base.
> Fix typos in iar_linker_script.icf.src

- test/packs/ARM/RteTest_DFP/0.1.1/ARM.RteTest_DFP.pdsc
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrGenerator.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestSolution/PackMetadata/metadata.cproject.yml
- tools/projmgr/test/data/TestSolution/PackMetadata/metadata.csolution.yml
- tools/projmgr/test/data/TestSolution/PackMetadata/ref/metadata.Debug+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/PackMetadata/ref/metadata.Debug+RteTest_ARMCM3.cprj
- tools/projmgr/test/data/TestSolution/PackMetadata/ref/metadata.cbuild-pack.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Strip build metadata when handling pack versions.
Throw a warning when specified metadata does not match the one from the loaded pack.
Addresses https://github.com/Open-CMSIS-Pack/devtools/issues/1339#issuecomment-1987962578
> [projmgr] Strip build metadata when handling pack versions

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
unclear warning csolution: required pack 'ARM::CMSIS-Compiler@2.0.0' is not loaded #1356
The warnings are now printed only if -d (debug) switch is specified
> Fix for issue #1356 (#849)

- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Run schema check over generated files when it's enabled.
Add missing `language-C`, `language-CPP`, `language` and `scope` in cbuild schema.
Allow whitespaces in cbuild contexts for alignment with `build-types` and `target-types` schema requirements.
https://github.com/Open-CMSIS-Pack/devtools/issues/1397
> [projmgr] Run schema check over generated files

- libs/rtefsutils/test/src/RteFsUtilsTest.cpp
- libs/rtemodel/include/RteKernel.h
- libs/rtemodel/src/RteKernel.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- libs/rtemodel/test/src/RteModelTestConfig.cpp
- libs/rtemodel/test/src/RteModelTestConfig.h
- test/local_packs/A/ARM.RteTestRequired.pdsc
- test/local_packs/L/LocalVendor.LocalPack.pdsc
- test/local_packs/R/ARM.RteTestRequiredRecursive.pdsc
- test/local_packs/S/PreInclude/MyLocalPreInclude.c
- test/local_packs/S/PreInclude/MyLocalPreInclude.h
- test/local_packs/S/PreInclude/MyPreInclude.h
- test/local_packs/S/SomeVendor.RteTest.pdsc
- test/packs/.Local/local_repository.pidx
- tools/buildmgr/cbuild/src/CbuildProject.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.h
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
* [projmgr] csolution usage of local_repository.pidx packs for convert, list packs, list components #1430
collection of  effective pdsc files
tests
> [projmgr] csolution usage of local_repository.pidx packs #1430

- .github/workflows/nightly.yml
The coverage jobs were encountering failures due to inaccessible secrets when invoked from other workflows during the nightly build. This modification improves the handling of secrets by allowing them to be inherited from the calling workflows.
LOT: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
> Inherit token on workflow_call

- libs/rtemodel/src/RteKernel.cpp
Bugfix: decrease memory footprint when parsing pdsc files
> Bugfix: decrease memory footprint when parsing pdsc files (#867)

- libs/rtemodel/src/RtePackage.cpp
- test/packs/ARM/RteTest_DFP/0.1.1/ARM.RteTest_DFP.pdsc
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
See https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/307
**Note**: This changes both the RtePackage.cpp file, but also the pdsc files used for testing, including something that looks like it was done to ensure that the releases were sorted.
> [rtemodel] Align implementation with specification

- libs/rtemodel/src/RteTarget.cpp
- libs/rtemodel/test/src/RteChkTest.cpp
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- tools/projmgr/test/data/TestSolution/LinkerOptions/linker.csolution.yml
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.AutoGen+RteTest_Board.cbuild.yml
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/linker.AutoGen+RteTest_Board.cprj
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest-Test-board_With.Memory.h
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest_ARMCM3.h
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Resolve board in RteTarget
fixes: Regions header file not processing information from <boards> #1468
Use consistent directory names with dots and dashes
> Resolve board in RteTarget (#888)

- tools/projmgr/src/ProjMgrGenerator.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Remove `configurable` endianness from target attributes for RteModel conditions compliance.
The attribute was being removed before CPRJ generation but not before the model processing leading to a misaligned cbuild.yml.
> [projmgr] Remove `configurable` endianness from target attributes

- libs/rtemodel/include/RteItem.h
- libs/rtemodel/include/RtePackage.h
- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- test/packs/ARM/RteTest_DFP/0.2.0/Layers/config1.clayer.yml
- test/packs/ARM/RteTest_DFP/0.2.0/Layers/config2.clayer.yml
- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestLayers/ref/config.cbuild-idx.yml
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1464
> [projmgr] Extend `configurations` node for layer discovery

- tools/buildmgr/cbuildgen/config/AC6.6.16.2.cmake
- tools/buildmgr/cbuildgen/installer/install.sh
- tools/buildmgr/test/integrationtests/src/CBuildIntegTestEnv.cpp
- tools/buildmgr/test/integrationtests/src/DebPkgTests.cpp
- tools/buildmgr/test/integrationtests/src/InstallerTests.cpp
Arm Compiler 6.16.2 is a long term maintenance version of the Arm Compiler 6 and shall be supported by CMSIS-Toolbox as well. The cmake supports CPUs that are not supported by the 6.16.2 compiler version. For these CPUs the compiler will report an error on invocation.
> Update and rename AC6.6.18.0.cmake to AC6.6.16.2.cmake

- libs/rtemodel/src/RteGenerator.cpp
- test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc
In case generator executable contains no extension,
try to append ".com", ".exe" and ".bat" to get real file name.
That is needed to launch an executable via CreateProcess() WinApi method
> Windows: discover generator's file extension

- tools/projmgr/include/ProjMgr.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/ExternalGenerator/extgen.cbuild-set.yml
- tools/projmgr/test/data/TestSolution/test_restricted_contexts.cbuild-set.yml
- tools/projmgr/test/data/TestSolution/test_restricted_contexts.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/1203
> Restrict --context-set to one identical target-type and only one build-type per context

- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
csolution convert crashes when using attr=config files for generated component and the files is missing in the gpdsc file #1442
Provide nullptr guard over rteFile
tests are pending: provided by
PR [projmgr] Expose crash when running csolution convert (#1442)
Avoid tests crash
> csolution crashes with config files for generated compoinents

- libs/rtemodel/src/RteTarget.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- libs/rtemodel/test/src/RteModelTestConfig.cpp
- libs/rtemodel/test/src/RteModelTestConfig.h
- test/projects/RteTestM3/RteTestM3NoComponents.cprj
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/core0.Debug+MultiCore.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/core1.Debug+MultiCore.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+CM0.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/TrustZone/ns.Debug+CM0.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/TrustZone/s.Debug+CM0.cbuild-gen.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project1.Debug+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project1.Release+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project2.Debug+RteTest_ARMCM3.cbuild.yml
- tools/projmgr/test/data/TestSolution/ContextMap/ref/project2.Release+RteTest_ARMCM3.cbuild.yml
* Do not create RTE_Components.h if no component is selected
* [projmgr] Do not emit reference to `RTE_Components.h` when it does not exist
---------
> Do not create RTE_Components.h if no component is selected (#926)

- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1529:
> -	Project is valid even when no connections from the project are being consumed
> [projmgr] Relax project provided `connections` validation

- tools/svdconv/SVDConv/src/ProductInfo.h.in
"CMSIS SVD Check / Coverter" -> "CMSIS SVD Check / Converter"
> Fix typo in SVDConv product name

- libs/rtefsutils/include/RteFsUtils.h
- libs/rtefsutils/src/RteFsUtils.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.h
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
When running `csolution convert -s /absolute/path/to/foo.csolution.yml`, the "RTE" directory should be placed within that structure and not where the csolution process happens to be executed from.
This is a regression in csolution 2.3.0 compared to 2.2.1 and was introduced by [this change](https://github.com/Open-CMSIS-Pack/devtools/commit/27678e9e3e631fd4e60ee2bf85fd818b8ae328ac#diff-2f6999444987cfc670f1760728ffcdcce7274b4493b1f3b159b1a5719e4409e3L511-L513). In the commit, the RTE directory is now generated without initializing the project, so the path to the project will be the empty string rather than the actual location on disk and as a result, it's created in the working directory rather than in the project tree.
I've added a test case to demonstrate the problem, but I don't know how …
> [projmgr] Generate RTE directory in project tree

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
When using the `$ProjectDir()$` access sequence, the expectation is to expand it to the path to where the cproject.yml is placed.
> [projmgr] Validate $ProjectDir()$ in output-dirs->cprjdir (#1570)

- tools/buildmgr/cbuild/src/CbuildModel.cpp
When using specific data structure we may end up with out of range exception (must have fix for 2.5.0 please)
> [buildmgr] improve relative path support

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestSolution/SelectableToolchains/cdefault.yml
- tools/projmgr/test/data/TestSolution/SelectableToolchains/ref/select-compiler.cbuild-idx.yml
- tools/projmgr/test/data/TestSolution/SelectableToolchains/select-compiler.csolution.yml
Rework `select-compiler`: store intersection of required version ranges instead of registered one
Requested in Open-CMSIS-Pack meeting from [2024-06-25](https://linaro.atlassian.net/wiki/spaces/CMSIS/pages/29358948421/Open-CMSIS-Pack+Technical+Meeting+2024-06-25)
Related to https://github.com/Open-CMSIS-Pack/devtools/pull/1581
> [csolution] Rework `select-compiler`: store required version ranges

- libs/rtemodel/src/RteProject.cpp
Fixes crash when deselecting a generated component
> Remove generated component when a bootstrap component is deselected

- tools/projmgr/include/ProjMgr.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/TestSolution/novalid_context.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1619
* [projmgr] csolution option --context-set inconsistency
* Added tests
> [projmgr] csolution option --context-set inconsistency

- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestLayers/genericlayers.cproject.yml
- tools/projmgr/test/data/TestLayers/no-layer-provides.cproject.yml
- tools/projmgr/test/data/TestLayers/no-layer-provides.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1621
> [projmgr] List layers: introduce `active` connect handling

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1636
> [projmgr] List layers: fix removal of subset configurations

- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestLayers/ref/variables-notdefined.cbuild-idx.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
1. Validate `context-set` selection with and without `--context` options. Consider each `--context` option can be partially specified and must be expanded before validation.
2. Remove left-over `cbuild-set.yml` reading in list layers. Its reading/writing is already done in `ProjMgr::ParseAndValidateContexts` for all commands.
> [projmgr] Fix `context-set` handling

- tools/projmgr/src/ProjMgrWorker.cpp
`Bvendor` is an [unrestricted string](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_boards_pg.html#element_board) and must be handled accordingly.
It should not be confused with `Dvendor` that uses predefined values listed in [Device Vendor Enum](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#DeviceVendorEnum) and may have [alternate names remapping](https://github.com/Open-CMSIS-Pack/devtools/blob/tools/projmgr/2.5.0/libs/rteutils/src/DeviceVendor.cpp#L70).
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1671
> [projmgr] Fix `Bvendor` handling (#995)

- libs/rteutils/include/RteConstants.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestAccessSequences/pack-access-sequences.cproject.yml
- tools/projmgr/test/data/TestAccessSequences/pack-access-sequences.csolution.yml
- tools/projmgr/test/data/TestAccessSequences/ref/pack-access-sequences+CM4-Board.cbuild.yml
- tools/projmgr/test/data/TestAccessSequences/ref/pack-access-sequences.cbuild-idx.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Handle `$Dpack$`, `$Bpack$` and `$Pack(vendor::name)$` access sequences as documented in:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#access-sequences
Note: use `::` as delimiter instead of `.`, as established by [pack name conventions](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/YML-Input-Format.md#pack-name-conventions).
> [projmgr] Add pack related access sequences handling

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Ensure the compiler selection is clean before processing the compiler precedence to avoid unexpected redefinition if the precedences are recalculated, for example after applying a generated layer (cgen) to the context processing.
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1674
> [projmgr] Fix compiler redefinition

- tools/projmgr/include/ProjMgrYamlEmitter.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp
Both generator output directory and RTE were created (in the latter case also with contents) when running a generator with the `--dry-run` flag. The idea of dry run was to only return the contents of the GPDSC without unnecessary work or file system access.
When the RTE directory is no longer updated when dry-running a generator, creation of the cbuild and cbuild-gen files need to ignore that files may be missing when adding the `constructed-files` node.
> Avoid creation of files when dry-running generator

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1658
> [projmgr] Skip missing `pname` error when layer variables are not defined (#1008)

- libs/rtemodel/src/RteTarget.cpp
- test/projects/RteTestM4/regions_RteTest_ARMCM4_FP_ref.h
- test/projects/RteTestM4/regions_RteTest_CM4_board_ref.h
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest-Test-board_With.Memory.h
- tools/projmgr/test/data/TestSolution/LinkerOptions/ref/regions_RteTest_ARMCM3.h
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1675
> [rtemodel] Adjust default heap in regions file according to total RAM (#1010)

- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrUtils.cpp
- tools/projmgr/test/data/TestSolution/ref/test_pack_selection.cbuild-pack.yml
- tools/projmgr/test/data/TestSolution/test_pack_selection.csolution.yml
- tools/projmgr/test/src/ProjMgrUtilsUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1687
> [projmgr] Add support for pack version operators `^` (compatible) and `~` (equivalent) (#1016)

- tools/projmgr/schemas/common.schema.json
Partly address https://github.com/Open-CMSIS-Pack/devtools/issues/1731
> [projmgr] Restrict `build-type` and `target-type` schema pattern (#1018)

- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Aligned with `cbuild-idx` location.
> [projmgr] Fix `cbuild-set` location when `--output` is specified (#1023)

- external/xerces-c.patch
The previous version of xerces-c is vulnerable to CVE-2018-1311, version 3.2.5 is fixed for that issue.
> Bump xerces-x to 3.2.5

- tools/buildmgr/cbuildgen/config/AC6.6.16.2.cmake
- tools/buildmgr/cbuildgen/config/CLANG.17.0.1.cmake
- tools/buildmgr/cbuildgen/config/GCC.10.3.1.cmake
- tools/projmgr/schemas/common.schema.json
This PR adds the remaining missing C and C++ language standards to AC6, GCC, and CLANG.
- add C standards gnu17 and gnu23
- add C++ standards c++23 and gnu++23
- fix C++ standards c++20 and gnu++20 incorrectly setting `-std=c++17` and `-std=gnu++17` on AC6
Fixes #1785
> [devtools] Extend `language-C` and `language-CPP` supported values

- .github/matrix_includes_buildmgr.json
- .github/matrix_includes_packchk.json
- .github/matrix_includes_packgen.json
- .github/matrix_includes_projmgr.json
- .github/matrix_includes_svdconv.json
- .github/matrix_includes_test_libs.json
- tools/projmgr/swig/go/CMakeLists.txt
Updated workflows to run with updated macOS runners
> Updated workflows to run with updated macOS

- libs/ymltree/src/YmlFormatter.cpp
- libs/ymltree/src/YmlTreeParserInterface.cpp
- libs/ymltree/test/YmlTreeTest.cpp
Process correctly YAML:Null when parsing and emitting YAML files
> Respect YAML::Null node by parsing

- libs/rteutils/include/RteConstants.h
- tools/buildmgr/cbuildgen/config/AC6.6.16.2.cmake
- tools/buildmgr/cbuildgen/config/CLANG.17.0.1.cmake
- tools/buildmgr/cbuildgen/config/GCC.10.3.1.cmake
- tools/buildmgr/cbuildgen/config/IAR.9.32.1.cmake
- tools/projmgr/include/ProjMgrUtils.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrUtils.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/templates/cdefault.yml
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Debug+CM0.cprj
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Debug+CM3.cprj
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Release+CM0.cprj
- tools/projmgr/test/data/TestAccessSequences/ref/test-access-sequences1.Release+CM3.cprj
- tools/projmgr/test/data/TestAccessSequences/test-access-sequences1.cproject.yml
- tools/projmgr/test/data/TestSolution/outputFiles.cproject.yml
- tools/projmgr/test/data/TestSolution/ref/outputFiles.Debug+Target.cbuild.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1549
> [devtools] Add option to output linker `map` files

- libs/rtefsutils/include/RteFsUtils.h
- libs/rtefsutils/src/RteFsUtils.cpp
- libs/rtefsutils/test/src/RteFsUtilsTest.cpp
- tools/projmgr/include/ProjMgr.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
* Validate created-for node against cmsis-toolbox manifest version
* Addressed review feedback
> Validate created-for node against cmsis-toolbox manifest version

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestGenerator/ref/test-gpdsc-project-files.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild-gen.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1560
> [projmgr] Fix classic generator's bootstrap content reporting

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestLayers/ref/no_compiler.cbuild-idx.yml
- tools/projmgr/test/data/TestLayers/ref/select.cbuild-idx.yml
- tools/projmgr/test/data/TestLayers/searchpath.cproject.yml
- tools/projmgr/test/data/TestLayers/variables-notdefined.cproject.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1873
> [projmgr] Fix optional empty layer report

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestLayers/genericlayers.csolution.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1841 and https://github.com/Open-CMSIS-Pack/devtools/issues/1850
> [projmgr] Skip processing candidate layers during detection phase

- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1779
> [projmgr] Fix path normalization

- libs/rtefsutils/src/RteFsUtils.cpp
- libs/rtefsutils/test/src/RteFsUtilsTest.cpp
- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/test/src/RteModelTest.cpp
- tools/projmgr/src/ProjMgrYamlEmitter.cpp
- tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/core0.Debug+MultiCore.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/core1.Debug+MultiCore.cbuild-gen.yml
- tools/projmgr/test/data/TestSolution/ref/TestProject3_1.Debug+TypeA.cbuild-gen.yml
- tools/projmgr/test/src/ProjMgrUtilsUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1826
Format path of license info
Update test cases
> [rtefsutils] Ensure canonical directory separator

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestProject/test_component_csub.cproject.yml
- tools/projmgr/test/src/ProjMgrWorkerUnitTests.cpp
Mitigate potential disruption due to stricter component resolution introduced in https://github.com/Open-CMSIS-Pack/devtools/pull/1861 addressing https://github.com/Open-CMSIS-Pack/devtools/issues/1650.
Extend missing component error message with a hint when a single match is found but it is not automatically resolved.
For example for a partial identifier `Device:Startup` aiming a component without default variant:
```
error csolution: no component was found with identifier 'Device:Startup'
did you mean 'Device:Startup&C Startup'?
```
> [projmgr] Add a hint in missing component error message

- tools/projmgr/schemas/common.schema.json
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1943
> [Schema] CMSIS Solution project format schema files for improved description (#1129)

- libs/rtemodel/src/RteProject.cpp
- libs/rtemodel/src/RteTarget.cpp
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/test/src/ProjMgrGeneratorUnitTests.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1894
From [comment](https://github.com/Open-CMSIS-Pack/devtools/issues/1894#issuecomment-2616013012):
>Without option --update-rte: when constructed files are missing, csolution recreates the files, but issues a warning indicated which file was recreated.
With option --update-rte: the constructed files are updated.
> [rtemodel, projmgr] Recreate constructed files unconditionally (#1147)

- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/include/ProjMgrRunDebug.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/include/ProjMgrYamlParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrCbuildRun.cpp
- tools/projmgr/src/ProjMgrRunDebug.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW2.cbuild-run.yml
- tools/projmgr/test/data/TestRunDebug/run-debug.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1953 and https://github.com/Open-CMSIS-Pack/devtools/issues/1947
> [cbuild-run] Implement extensions (`system-resources`, `debug-vars`, `debuggers`)

- tools/projmgr/src/ProjMgrCbuild.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2004
> [projmgr] Skip `dbgconf` output when not provided by user nor by DFP

- .github/workflows/buildmgr.yml
- external/json-schema-validator.patch
- external/json.patch
- external/yaml-cpp.patch
- libs/rtemodel/test/src/RteExampleTest.cpp
Failure occurred due to the deprecation of support for CMake versions earlier than 3.10. Since the Ubuntu GitHub runner uses CMake 3.31.6, which no longer supports versions prior to 3.10 in many cases, our pinned version of GoogleTest needed an update. Additionally, other dependencies, such as JSON and JSON Schema Validators, were updated to the minimum compatible versions, with 3.5 being the lowest supported.
https://cmake.org/cmake/help/latest/release/3.31.html#deprecated-and-removed-features
The change includes:
- Pin googletest to latest v1.16.0
- yaml-cpp patch update `cmake_minimum_required(VERSION 3.10)`
- json patch update `cmake_minimum_required(VERSION 3.10)`
- json-schema-validator patch update `cmake_minimum_required(VERSION 3.10)`
- Updated ubuntu-20.04 to ubuntu-22.04. …
> Updated googletest version to v1.6.0

- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrRunDebug.cpp
- tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2041:
- Emit static information for all processors regardless of context selection
- When relevant add `pname` for each `output`
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2042:
- Populate `accessports` considering PDSC `<debug>` info
> [cbuild-run] `debug-topology` refinements

- tools/projmgr/templates/cdefault.yml
fixing #338
C runtime library linking changed in version LLVM/CLANG 20.1.0 We are accepting that projects using previous version will need to add `-lcrt0` manually to the project when relying on `cdefault.yml` from `$CMSIS_TOOLBOX/etc`
> remove crt0 library from linker command

- tools/projmgr/src/ProjMgrRunDebug.cpp
- tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml
Changes after feedback from @RobertRostohar:
- start listing `gdbserver` `port` from the `start-pname`
- set `debug-topology` `processors` according to `apid` order
> [cbuild-run] Rework gdbserver ports and processors order

- tools/projmgr/test/data/TestSolution/outdirs-absolute.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
The test case `OutputDirsAbsolutePath` is intended to catch a non-portable absolute path on Windows.
GH Runners for win-amd64 started to use the `C:` drive letter instead of `D:`, hiding the portability issue under test and causing the [test failure](https://github.com/Open-CMSIS-Pack/devtools/actions/runs/15009141329/job/42192679789).
This PR sets an UNC path `\\non_existing_cmsis` in the non-portable absolute path under test, restoring the expected test behavior.
> [projmgr] Update test case `OutputDirsAbsolutePath`

- tools/projmgr/src/ProjMgrRunDebug.cpp
- tools/projmgr/test/data/TestRunDebug/run-debug.csolution.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2085
> [cbuild-run] Use case insensitive for debug adapters search

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrRunDebug.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/TestRunDebug/core1.cproject.yml
- tools/projmgr/test/data/TestRunDebug/ref/run-debug+TestHW3.cbuild-run.yml
- tools/projmgr/test/data/TestRunDebug/run-debug.csolution.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2080
> [projmgr] Handle `load` mode for `project-context`

- libs/rtemodel/src/RteFile.cpp
- libs/rtemodel/test/src/RteItemTest.cpp
for the case the top group name is empty
> Fix GetHierarchicalGroupName() (#1267)

- test/packs/ARM/RteTest_DFP/0.2.0/ARM.RteTest_DFP.pdsc
- tools/projmgr/include/ProjMgr.h
- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2151
In the typical use case the results are filtered according to the [template's conditions](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_csolution_pg.html#element_cs_template) evaluated for the selected target type:
```
$ csolution list templates <csolution.yml> -a <active target set>
<template name> (<pack>)
```
When the *.csolution.yml is not specified it lists all templates from installed packs.
The `--filter` option checks the presence of a filter string in the`<template name>`.
When the `--verbose` flag is used further information is printed:
```
<template name> (<pack>)
description: <template description>
path: <path to template's folder>
file: <path to *.csolution.yml file>
copy-to: <destination …
```
> [projmgr] Add `list templates` command

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address feedback https://github.com/Open-CMSIS-Pack/devtools/issues/2140#issuecomment-3089690055
- do not print `components`, `categories`, `keywords`
- search for `--filter` only among example names. Do not add further command line options to avoid asymmetry with other `list` commands. In RPC methods `board`, `device` and `environment` will be input parameters and the results will be filtered accordingly.
- handle `--verbose` flag
- print "Reference Application:" before such examples (hardware agnostic examples)
- filter out "Reference Applications" for boards that do not have `clayer` with type `Board`
> [projmgr] Update `list examples` command

- tools/projmgr/include/ProjMgr.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2109
`list debuggers` prints a plain list of debugger adapter names from debug-adapters.yml file, for instance:
``` shell
CMSIS-DAP@pyOCD
CMSIS-DAP@Arm-Debugger
```
`list debuggers --verbose` prints additionally their aliases, for example:
``` shell
CMSIS-DAP@pyOCD
CMSIS-DAP
DAP-Link
CMSIS-DAP@Arm-Debugger
CMSIS-DAP@armdbg
```
> [projmgr] Add `list debuggers` command

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgrRpcServer.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrRpcTests.cpp
Implement https://github.com/Open-CMSIS-Pack/csolution-rpc/pull/24
Partly address https://github.com/ARM-software/vscode-cmsis-csolution/issues/284
> [csolution-rpc] Handle `GetDraftProjects` method

- tools/projmgr/include/ProjMgr.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Accept command line option `--active` with empty argument, implicitly taking the first `target-type` as the active one.
Being `--active` a "string option" rather than a "boolean flag", to be correctly parsed the "empty argument" needs to be in one of the formats:
```shell
--active=
--active ""
-a ""
```
Note `-a=` is not supported. In such case `=` is literally the argument.
Align with https://github.com/Open-CMSIS-Pack/cbuild/pull/443
> [csolution] Handle cmd line option `--active=` (empty argument)

- test/packs/ARM/RteTestGenerator/0.1.0/ARM.RteTestGenerator.pdsc
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/core0.Debug+MultiCore.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/MultiCore/core1.Debug+MultiCore.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+Board.cbuild.yml
- tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+CM0.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/SingleCore/single-core.Debug+CM0.cbuild.yml
- tools/projmgr/test/data/ExternalGenerator/ref/TrustZone/ns.Debug+CM0.cbuild-gen.yml
- tools/projmgr/test/data/ExternalGenerator/ref/TrustZone/s.Debug+CM0.cbuild-gen.yml
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2165
> [projmgr] Remove filtering of component files having `gen*` categories

- tools/projmgr/include/ProjMgrParser.h
- tools/projmgr/schemas/common.schema.json
- tools/projmgr/src/ProjMgrRunDebug.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/src/ProjMgrYamlParser.cpp
- tools/projmgr/test/data/ImageOnly/image-only-multicore.csolution.yml
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/devtools/issues/2176
> [projmgr] Handle processor name for user specified `image`

- tools/projmgr/src/ProjMgr.cpp
The `-R, --relative-paths` option for the `list packs` command was introduced as test support in https://github.com/Open-CMSIS-Pack/devtools/pull/1221 but should be excluded from usage/help page (hidden option).
Reported by @ReinhardKeil
> [projmgr] Remove `-R, --relative-paths` option from usage page

- tools/projmgr/CMakeLists.txt
- tools/projmgr/include/ProjMgr.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrRpcServer.cpp
- tools/projmgr/test/data/TestRpc/minimal.csolution.yml
- tools/projmgr/test/src/ProjMgrRpcTests.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.cpp
- tools/projmgr/test/src/ProjMgrTestEnv.h
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/406
Start addressing https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/408
- Handle `LoadSolution` method request with `activeTarget` parameter
- Add `apiVersion` to `GetVersion` method response
- Add`ConvertSolution` method handling
> [projmgr] Add `ConvertSolution`, update `LoadSolution` and `GetVersion` RPC methods

- tools/projmgr/include/ProjMgrWorker.h
- tools/projmgr/src/ProjMgr.cpp
- tools/projmgr/src/ProjMgrWorker.cpp
- tools/projmgr/test/src/ProjMgrUnitTests.cpp
Address https://github.com/ARM-software/vscode-cmsis-csolution/issues/312
> [projmgr] Skip cbuild-run generation when target-set has only `lib` contexts
